### ISSUE TITLE
Upload collection not picking up some cards

### ISSUE THREAD

**Issue by immortius** [Senryoku/MTGADraft#10]
I and my friends have noticed an issue where some cards (generally white) are not being picked up from the MTGA log when importing a collection.

Using Theros Beyond Death as an example, Captivating Unicorn, Daybreak Chimera and Dreadful Apathy commons are missed, as are a number of uncommons. These are also shown at the bottom of the Collection Statistics as oppose to at the top with the other white cards (after not-in-booster cards).

![image](https://user-images.githubusercontent.com/1388872/79040984-a57d9780-7c2f-11ea-85bf-047c0eca4452.png)

**Comment by Senryoku** [comment]
Good catch, it's easy to reproduce, looks like there's a problem with at least the first cards of Theros (Collector Number 1 to 14, Arena IDs 70801 to 70814) when importing a collection. Not sure what's causing it for now.
Thank you for the report.

**Comment by Senryoku** [comment]
Should be fixed by 4053b1714eb8bbbc5cfc3a59131c571c0eb6dda9

**Comment by immortius** [comment]
Fix works for me, thank you for the speedy fix.
