### ISSUE TITLE
Randomize seating without clicks

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#100]
I think @Senryoku doesn't want to auto-shuffle seating, because it could be confusing/frustrating if you assign the seats and then they change, and I definitely think we need both an option for random seats and one for assigned seats. 80.9% of respondents in Survey #1 wanted some form of automatic shuffling, but it's possible the question wasn't phrased right. An idea for making progress on this: keep the shuffle button and the ability to assign seats, but have people "sit down" into random seats, so that you're always seeing the seating order that the draft would start with, but even if you don't take any special action you end up with a randomized draft order (versus one where joining time influenced the seating order).

**Comment by Senryoku** [comment]
Implemented the proposed solution here: 5a0908b48787553ffa91bd0c39ba4f98e726972f
Players are randomly inserted in the userOrder array instead of pushed at the end.

**Comment by wrmacrae** [comment]
Nice, looks like it should work to me. I recall a number of tests that depended on the owner being in the first seat, and saw that you got one and I think I've fixed a handful others. I'll pull this and try to be sure that the change didn't add new test flakes, but I think the issue is solved!
