### ISSUE TITLE
Owner disconnects have been problematic

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#101]
From survey #1 free response: "way to survive the crown player crashing out"

**Comment by Senryoku** [comment]
I'm not sure if I understand this one correctly. 
If this means "being able to continue the draft after the session owner was disconnected", I've recently (1c83d9a2395fe2ff3f0107330b603fcd1cef1cbd) modified the disconnect message to include the updated owner ID to make sure the new owner is prompted with the correct version of the popup and is able to replace the disconnected player with a bot.

**Comment by wrmacrae** [comment]
Nice, the comment in the survey was from August 6 (I put the results in a sheet to see timestamps), so your fix was after this feedback and likely addressed it!
