### ISSUE TITLE
Improve Mobile UI

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#105]
I've never looked at the app in Mobile, but on Survey #1 someone indicated it could use some improvement.

**Comment by wrmacrae** [comment]
Here's at least one thing to handle if testing doesn't reveal other problems (Survey #1 free response):
> I wish it didn't show the "player disconnected" popup alert every time my phone goes dark/sleeps

**Comment by wrmacrae** [comment]
I think Survey 2 should have Mobile Improvements as a section we gather interest on, so that we can decide how deeply to investigate this.

**Comment by Senryoku** [comment]
Low priority according to the survey.
