### ISSUE TITLE
Make "Glimpse/Burn Draft" easier accessible

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#108]
Make "Glimpse/Burn Draft" easier accessible and give it a name.

I would like to see "Glimpse/Burn" as an option in the other games modes dropdown menu as well.
Clicking it should ask for the amount of cards to burn (defaulting to 2) and the amount of packs per player (defaulting to 9) just like winston draft ask for the amount of packs in the main pile.

That way this game mode - while already possible - become more visible to the ordinary user.
People that might not be aware of the format just don't get that you can play it as it's a hidden custom setting that needs to get adjusted with the right value in order to play it. The host also needs to add more boosters per person via the advanced settings.

**Comment by Senryoku** [comment]
Good suggestion, I've drafted a quick implementation here https://github.com/Senryoku/MTGADraft/pull/111 if you want to double check (The description of the format can probably be improved)

**Comment by tooomm** [comment]
Looks good!
Don't you want to mention the alternative name "Burn"?

<br>

>The description of the format can probably be improved

`Glimpse Draft is a draft variant where players remove cards from the draft (typically 2) alongside each pick. It's mostly used for small and medium sized groups where a regular draft makes not much sense.`

A "More information" link could point to http://turnonemagic.com/glimpse-drafting-best-way-draft-cube-2-4-players-title-shorter/

**Comment by Senryoku** [comment]
Thanks, I updated the description and merged the changes.
Yeah, it's one of the first results for Glimpse Draft on Google, but while a wiki link seemed appropriate for Winston Draft, I don't want to add a link to a website I don't know. I think your description should be good enough!

**Comment by tooomm** [comment]
Always a pleasure to help and see changes incorporated that quickly. 👍
