### ISSUE TITLE
More realistic collation

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#113]
A common request/question in Discord, on the survey, and on Twitch chat has been about whether we do collation of cards correctly. There are good resources out there for how paper collation worked in recent sets, for example here: https://www.youtube.com/watch?v=kct0tF0qgdk I've never heard an opinion or analysis either way about whether Arena uses the paper collation rules, but imo we should mimic Arena whatever that is.

I pulled up a pack from an Ikoria draft log https://www.17lands.com/draft/67f5818d36ee481bacb3d7eccfde3fbb/3/1 and compared the commons to the print run of Ikoria https://docs.google.com/spreadsheets/d/1cnnB4iPSXsBZNGIa7K5XnQsFAHQtTUVqa_wQ1mfLjq8/edit#gid=0 (English/US in both cases, though I'm not sure if that matters). I think that pack has several things that show Arena does not use the collation rules of paper:
- Glimmerbell without any of its 3 neighbors in Run A (or the last card, if the runs loop, since it appears at the beginning)
- Phase Dolphin without any of its 4 neighbors in Run A
- Rumbling Rockslide without any of its 4 neighbors in C1

If someone has more information on Arena collation, that would be really useful, but for now, based on the logs I've seen and this comparison to the print collation, I think it's best to assume that cards are selected randomly with the same color balance restriction that we default to. Similarly, if anyone has logs of an Arena pack without color balance, that would be important to know. But I'm going to close this issue since I think our collation is as realistic a representation of Arena as we know, and I'm just filing for tracking.

**Comment by Senryoku** [comment]
Lots of information on paper collation for future reference: https://www.lethe.xyz/mtg/collation/

**Comment by wrmacrae** [comment]
This site is awesome! Can confirm my earlier comment (at least on Glimmerbell) still applies. It seems like Arena doesn't use the collation rules from US/English boosters even when playing in English in the US - seems more likely it's picking cards randomly within rarity like we do.
