### ISSUE TITLE
Track multiple drafts for a user

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#114]
This is an enhancement we can survey for interest on Survey 2. It would be nice to give a user the logs of their past drafts, with basic information about those drafts even after they have completed other drafts.

**Comment by Senryoku** [comment]
You can currently download the draft log in json and re-open it using a very poorly placed button at the bottom of the page (the only place where it made sense to me was in the draft log popup, but it's not accessible if you don't have a draft log saved in the browser currently).


The more I think about it, the more I realize this could be an opportunity to improve the draft log UI, regardless of user interest for long term storage.

**Comment by Senryoku** [comment]
Tried a couple of things there: https://github.com/Senryoku/MTGADraft/pull/121
Looking for feedback!

**Comment by Senryoku** [comment]
2260a2d892a99984ceb670b0f758b8349ed30f8a
