### ISSUE TITLE
Share or submit decks once built

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#115]
This is an enhancement we can survey for interest on Survey 2. If users build their deck inside of the app, they should be able to share the final deck within the app. This would need options like draft logs for who could see it, or to use the same permissions, and an option to lock in submissions (or at least timestamps for when things were submitted). This might eventually allow people outside of the draft to follow better via the bracket page, and could help with tournaments where deck submission is an important step.

**Comment by tooomm** [comment]
Building on the conversation in https://github.com/Senryoku/MTGADraft/pull/110#issuecomment-699553232
>I agree about seeing what decks players ended up making in the app, it's one of the next major things I want to work on, and I've been tracking it here: #115 . I'm having some difficulty figuring out all the right spots to add it to the UI (logs, bracket, player seating) in the cleanest way, so would appreciate thoughts over there.


Populate the decks into brackets and next to player names in the pool would be nice.

I will follow your PR, but out of my head these obvious places come to my mind:
- logs: Have a new `Decks` option in the log dropdown, same like `Picks` and `Cards`
- player seating: New icon next to name
- bracket: Same icon next to name
