### ISSUE TITLE
Trophy leaderboard

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#116]
This is an enhancement we can survey for interest on Survey 2. While one could certainly abuse this feature, having a basic indications of which users have won which drafts can be really fun and motivating, and might make the app stickier. I have a few thoughts on handling abuse, but when there aren't really many stakes, I think just having an unofficial thing up may get good engagement without too much complexity.

**Comment by Senryoku** [comment]
We don't have persistent storage right now (disregarding the DynamoDB used to restore sessions over reboot which is not ideal). We'd probably have to figure out a new hosting solution at this point.
