### ISSUE TITLE
Display foils as... foils in front end?

### ISSUE THREAD

**Issue by aloisdg** [Senryoku/MTGADraft#12]
Hello,

This issue will be use to talk about the foil effect.
As far as I know, there is no way to have a foil print image through Scryfall. I hope you can correct me. An alternative would be to rely on a foil effect in the frontend. It is quite easy to achieve and in fact this is how the website [archidekt handle it](https://archidekt.com/decks/482757#[Standard]_Sultai_Undergrowth_(IKO)). Lets implement this effect in MTGADraft!

I start working on it and the result works quite well imho:

![image](https://user-images.githubusercontent.com/3449303/79042016-6c740180-7bf4-11ea-9602-1e58101a7adc.png)

**Comment by Senryoku** [comment]
I was thinking about something more discreet, like the old foil symbol:
![](https://deckmaster.info/images/sets/PRM_C.png)
What kept me from adding it until now is the need to store and send some metadata along with the booster, prompting changes in multiples places. Right now a "booster" is just a list of Arena IDs.

**Comment by aloisdg** [comment]
@Senryoku I am not sure what would be the benefit as a arena player though. I finished the implementation I will open a PR with the frontend. Feel free to ignore it for now :)

**Comment by tooomm** [comment]
@aloisdg Did you ever open that PR?

As long as there is a foil option, I think it's very nice to show such cards it in the frontend during drafting and building on the page at least. For the area import they could be normal cards.
Otherwise it's mostly impossible to know if the option is working at all.

**Comment by Senryoku** [comment]
49c8bf53c15043518362cbe3309756254c3db23e
