### ISSUE TITLE
Setup heroku review apps

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#122]
It's a super nice feature to easily test new changes right from the PR:
https://devcenter.heroku.com/articles/github-integration-review-apps

That way everybody can give feedback and test changes right away.

They should work fine even in the free tier as they don't eat up much time even when automatically created for each PR.

**Comment by Senryoku** [comment]
Thanks for the suggestion, I didn't know this feature, it's now enabled!
