### ISSUE TITLE
Is it normal that a pack may contains two rares?

### ISSUE THREAD

**Issue by aloisdg** [Senryoku/MTGADraft#13]
Hello,

I got a booster with two rares:

![image](https://user-images.githubusercontent.com/3449303/79042441-24ef7480-7bf8-11ea-8c6a-037028e583d9.png)

This never happened as far as I know in MTGA. I guess the first one is a foil and a foil can be a rare. So two rares or I guess one rare and one mythic rare can be found in a single pack?

related to https://github.com/Senryoku/MTGADraft/issues/7

**Comment by Senryoku** [comment]
The first one is a foil that happens to be rare yes.

**Comment by aloisdg** [comment]
The more I think about it I think that foild should no be check per default if we are looking to simulate mtga draft.

I close the issue though.
