### ISSUE TITLE
Change set order in drop down menu (e.g. in collection statistics)

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#135]
The `Select set` dropdown at top starts with some keywords for groups of certain sets, followed by the oldest sets first to the newest at the very bottom.
With a growing list it also gets tedious to select newer sets. For sets selection on main page you do recent sets on top already.

Also, is it possible to include like a separation line (or empty line) to visually divide individual sets (`ZNR`, `M21` etc.) from group of sets (`All`, `Standard` etc.) in the dropdown?

```
All
Standard
Other Sets
 -----
Zendikar Rising
Amonkhet Remastered
Core Set 2020
.
.
.
```

**Comment by Senryoku** [comment]
I've reversed the order of sets.
Also tried adding a separator and I'm honestly not a fan (don't pay attention to the order in the screenshot :))
![image](https://user-images.githubusercontent.com/1338143/95235750-4a0b1b80-0806-11eb-907f-1ee12bbd9b38.png)
(It's pretty hacky (disabled option) and not aesthetically pleasing imho)

**Comment by tooomm** [comment]
>I've reversed the order of sets.

Hmm, there seems to be an issue with the sets drop down in stats and the drop down in additional session options for the boosters.

They behave weird and swap order sometimes.

<br>

>Also tried adding a separator and I'm honestly not a fan
It's pretty hacky (disabled option) and not aesthetically pleasing imho

In your screenshot it looks very appealing to me! :D
What do you dislike about it (besides the hacky implementation)? I assume you can still select it and it could have an unexpected result for the user? That would not be ideal... yeah.
I think it looks super clean though and separates both types well.

Do you have a different idea for solving this?

**Comment by Senryoku** [comment]
> 
> 
> > I've reversed the order of sets.
> 
> Hmm, there seems to be an issue with the sets drop down in stats and the drop down in additional session options for the boosters.
> 
> They behave weird and swap order sometimes.

Oh, yeah, reverse() operates in place, oops. 

> 
> > Also tried adding a separator and I'm honestly not a fan
> > It's pretty hacky (disabled option) and not aesthetically pleasing imho
> 
> In your screenshot it looks very appealing to me! :D
> What do you dislike about it (besides the hacky implementation)? I assume you can still select it and it could have an unexpected result for the user? That would not be ideal... yeah.
> I think it looks super clean though and separates both types well.
> 
> Do you have a different idea for solving this?

You can't select it, but it just doesn't look right to me and options can't be styled using CSS.
No real solution other than completely re-writing a dropdown component, so I just pushed it as-is.

Firefox:
![image](https://user-images.githubusercontent.com/1338143/95329347-16cc9900-08a7-11eb-9a64-e2d9a96e9f37.png)
Chrome:
![image](https://user-images.githubusercontent.com/1338143/95329381-21872e00-08a7-11eb-97a7-2d780ce358f1.png)

**Comment by tooomm** [comment]
I like the result a lot!

As the order is now most recent on top in all set drop downs this issue is fixed.
