### ISSUE TITLE
Improve team draft logs

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#136]
Two improvements suggested by @tooomm :
- Log shows two players as (empty) instead hiding them out for Team Draft logs.
- There are no team colors shown in logs for Team Draft logs.

Plus I should just test and look at team draft logs and see if there are other things to improve - I didn't look at logs at all while building team drafts.

**Comment by tooomm** [comment]
>   - Log shows two players as (empty) instead hiding them out for Team Draft logs.
>   - There are no team colors shown in logs for Team Draft logs.


Following the most recent "LR vs. LoL Showdown" Kaldheim Edition I realized that logs for Team Draft show both issues again:
![teamdraft](https://user-images.githubusercontent.com/9874850/106398128-5c424280-6411-11eb-8c59-df22f80c1401.png)


Also note, that ideally the game type in the logs should show `Team Draft` as well.

**Comment by Senryoku** [comment]
I distinctly remember staring at the "a < 6 || a === 7" condition and failing to understand why it was not equivalent to "a < 8"... *sigh*
We'll just say I was tired :D

Anyway, should be fixed by 7382f481c014eb68fc8a98507b3576af0794a48e and displaying "Team Draft".
Thanks!

**Comment by tooomm** [comment]
Awesome 😄
