### ISSUE TITLE
Color balancing significantly decreases colorless common odds

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#139]
If I'm reading the color balancing logic correctly (https://github.com/Senryoku/MTGADraft/blob/31b33940f351bcdeda64508566d9bdacec2f13f8/src/BoosterFactory.js#L80-L95), colorless commons (and also maybe gold ones) appear at roughly 50% of the frequency of mono-colored commons when color balancing is on, because 5 of the 10 common slots are seeded with colored cards. We should figure out a way to collate such that we maintain color balancing, but each common has similar probability of appearing in a pack.

**Comment by Senryoku** [comment]
Applied the fix to cube too with 0c5944a151cc1efd90e0a8795e1f800e21a29371
