### ISSUE TITLE
Allow up to 32 player for e.g. Sealed tournaments

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#140]
For draft it shouldn't matter as it's mostly always max. 8 players.
But Sealed can easily support like 20-30 players for a tournament.

Is there a particular reason to limit the max players to 16 only? Any concerns on performance, user managmenet or server load?

**Comment by Senryoku** [comment]
No good reason :) Removed the limit here 5b26fccf6d607321fd53584f434bef85a393889f
