### ISSUE TITLE
Double elimination brackets

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#144]
Feature request from discord: add a button to generate double-elimination brackets. For example: https://images.ctfassets.net/ryplwhabvmmk/4gC73RyMKnDjVbaG8eKr8S/b849d6c5bfea65592f7df9c93850cc45/2020-Season-Grand-Finals-Bracket-Final.jpg?w=1440&q=70

**Comment by Senryoku** [comment]
Tentative implementation testable here:  #272
