### ISSUE TITLE
Vertical creature/non-creature divide while brewing

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#145]
FR from discord: Arena's filtering allows you to put cards into columns by CMC (or custom placement) as we do, but they you can split vertically by a filter, and the most commonly used one is "t:creature" which puts creature cards in a section above non-creature cards like this https://cdn.discordapp.com/attachments/698808214069968966/759147155368706069/Screenshot_from_2020-09-25_23-18-51.png

It would be nice to add a feature to see the same view temporarily while building decks.

**Comment by Senryoku** [comment]
I'm all for more options for deck display, but I'm already unhappy with the CardPool component behaviour with different screen sizes. I tried to avoid column wrapping by adding an horizontal scrolling when needed, but never managed a flawless implementation (details are eluding me right now, I'd have to try again).

Adding a second row when they can wrap and column can shrink when empty would be pretty confusing. Maybe we could (dynamically) adapt the column count to the screen size and keep it fixed?

**Comment by tooomm** [comment]
>I'm already unhappy with the CardPool component behaviour with different screen sizes. I tried to avoid column wrapping by adding an horizontal scrolling when needed, but never managed a flawless implementation

That is indead not ideal. The wrapping columns are really confusing!
LSV struggled with that a lot during the streamed Team Draft event. It was clear that he was new to the site and couldn't figure things out intuitively.

Scrolling sounds nice, but it would hide some columns on smaller screens.
What about this... did you try shrinking the deck display area?
The size of the displayed cards could adjust according to the amount of columns enabled and available screen size. Of course this would lead to smaller pictures when many columns are used or only a small screen/small resolution is available. But I doubt that in a normal setup it leads to issues and the user experience might benefit a lot.
Also there is the card zoom feature!

**Comment by wrmacrae** [comment]
Filed #155 with some ideas (not all my own) on column wrapping problems, since I think we should track that as a new issue

**Comment by tooomm** [comment]
After solving the wrapping issue in #160, this is back on the table again.
