### ISSUE TITLE
Deck sharing: export button clarity

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#148]
When viewing a shared deck in the draft log, there are a lot of export buttons and it's not very clear which export the log vs the deck. We should clean up the language and add tooltips and other visual queues so that it's more obvious to users what they will export when clicking each of those buttons. The underlying functionality of these buttons doesn't need to change at all, though.

**Comment by Senryoku** [comment]
Is this enough? 71b40532b01ddd98c1883ec08237defdd546ce06

**Comment by tooomm** [comment]
I propose to simplify and combine the various export options and buttons into one.

Like the dropdown for `Other game modes` it would be labeled `Export Deck as`, and the user selects from `MTGA, Simple Text List` and potentially other in the future. Clearer UI with less buttons but same functionality.

**Comment by Senryoku** [comment]
> I propose to simplify and combine the various export options and buttons into one.
> 
> Like the dropdown for `Other game modes` it would be labeled `Export Deck as`, and the user selects from `MTGA, Simple Text List` and potentially others in the future. Clearer UI with less buttons but same functionality.

I feel like this is unnecessary as long as we only have two options, but I'll definitely do that if we add any additional variation.

**Comment by tooomm** [comment]
It would help with the cluttered interface, even though there are "only two" export options currently.
The user always needs only one of them at a time.

**Comment by wrmacrae** [comment]
Thanks, I like these button names and tooltips, should be easier to navigate now!
