### ISSUE TITLE
Problems with deck hashes

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#150]
Some tests with ZNR showed the wrong deck hash for Cockatrice. Can't speak for MWS.
Didn't test other sets so far. More investigation needed.

Deck hashes got implemented in https://github.com/Senryoku/MTGADraft/commit/b59efc892a51d4c992bda44422fa263c3052d455 as part of https://github.com/Senryoku/MTGADraft/pull/138, see https://github.com/Senryoku/MTGADraft/pull/138#issuecomment-703071164 for some more information.

**Comment by Senryoku** [comment]
Thanks for the report, found a problem with MDFCs and fixed it with d33edde36ecbb670bc299c2c4b41006776c69d22

**Comment by tooomm** [comment]
Jep, works correctly now.

I also realized some issue with exporting - but you beat me to it. Hehe.
