### ISSUE TITLE
Increase duration of layover pop ups slightly

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#152]
When e.g. sharing your deck there is a little pop up shown on the upper right corner that sais "Deck now visible in log and bracket". I feel like the duration is kinda short in order to properly read it.

What do you think about increasing it for one second for example?

**Comment by Senryoku** [comment]
Sure, I see no downside. Increased the duration of these popups to 3sec b76d288d8408eac150ad628bca0e257ec01337f8
