### ISSUE TITLE
Enhance dropzone when drag picking

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#153]
It would be nice to not only put cards in your deck no matter where you drop them and order them according to the currently selected pattern, but to allow to drop them to a specific column right away.

Right now you have to drag a card to your deck (or double click it) to add it to your pool. It then appears in one of the columns automatically. You then have to find it and manually move it to your preferred place.

LSV struggle in the Podcaster Team Draft Showdown a lot with this. :)
Seems like a very useful addition to me!

**Comment by wrmacrae** [comment]
Suggest we close, @tooomm per https://github.com/Senryoku/MTGADraft/pull/160
