### ISSUE TITLE
Deck sharing: Add icon next to player name

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#154]
Have e.g. an icon next to the player name in brackets which visualizes who submitted their deck already.
Similar to the uploaded card collection with different colours and tooltips.

Currently you have to click all player names and check the section below the bracket if their deck is available yet. That would help with organizing the pod.

(The same could apply for names in the user list/player seating)

**Comment by Senryoku** [comment]
Added an icon in draft log and bracket in d086fc421990479787f1f31eb5889ab3ff0e2cb7. I don't want to add another icon to the player seating, space is already pretty tight there.
![image](https://user-images.githubusercontent.com/1338143/96272014-d7502c00-0fcd-11eb-876c-ecf80d26838b.png)

**Comment by tooomm** [comment]
>I don't want to add another icon to the player seating, space is already pretty tight there.

Sure, that's understandable.

As always super quick... No chance to test this on the page yet.

**Comment by tooomm** [comment]
Jep, that works.

Can clicking that icon in logs result in jumping to the `Deck` view right away instead the default `Cards` when clicking the name?

**Comment by Senryoku** [comment]
> Jep, that works.
> 
> Can clicking that icon in logs result in jumping to the `Deck` view right away instead the default `Cards` when clicking the name?

Wep, good idea! 11206621c04b5dc11735f711842d075785d17ff7

**Comment by tooomm** [comment]
It jumps right to the deck now, but also had some issues. Will try to check in some real games... leaving this open. Will take a while until I get to it probably.

**Comment by Senryoku** [comment]
I guess this one can be closed :)
