### ISSUE TITLE
Add columns when dragging cards to right of rightmost column

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#156]
semi-related to #153 - I saw some struggling with trying to drag cards to the right when there weren't columns there yet. If a user drags a card to the right of the rightmost column we should add a new column and put the card there.

**Comment by tooomm** [comment]
To visually stress that something like that works, the `+` button could be highlighted when dragging to the right end and on drop create the new column.

**Comment by wrmacrae** [comment]
https://github.com/Senryoku/MTGADraft/pull/160
