### ISSUE TITLE
Have titles for columns in deck sorting + card count in piles

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#157]
It would help with navigation in, arrangement and overall handling of your deck a lot.

- **Titles for columns in deck sorting**
Could be above/at top of the column box as a typical headline title, or even at the bottom of the column box as a more subtle hint.

    E.g in CMC mode
    ```
    0   1   2   3   4+   etc.
    .   .   .   .   .
    .   .   .   .
    .           .
            .
    ```

    E.g in rarity mode:
    `Common`, `Uncommon`, `Rare`...

    And so on for colour and type as well.

<br>

- **Card count per column/pile**
Including a count as well to show you the quantity of cards in that pile.
Could be in brackets behind the title or in the lower corner of the column for example.

[Edit(Senryoku)]
- Use this header to add a "Remove this column" button.
(From #176)
- Keep Track of current sorting option (and highlight it)

Also, two other related, minor things:

 - The black color bar in the sorting by color option is not very well visible - maybe use "Plains" instead "Swamp" color?
 - I think a gap between the group of column options (+/-) and the group of sorting options (cmc, color, rarity...) would be helpful as well

**Comment by wrmacrae** [comment]
I really like having the card count for columns! But I'm less on board with labelling the columns, because after sorting you can start modifying the columns, and the labels will gradually make less sense, so it won't be clear to us when we should get rid of them as you drag cards around. Curious if you have an idea for how to handle that user experience.

**Comment by tooomm** [comment]
Good point. The first thing that pops to my head is that the titles could get greyed out once cards in the pile doesn't fit the sorting anymore.
