### ISSUE TITLE
Issues with card zooming

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#164]
From https://github.com/Senryoku/MTGADraft/pull/160:
>When you right-click a card to see a larger version of it, that seems to be a percentage of the original size, but I think it should be an absolute width instead. If you end up with very small columns, the percent-larger card might still be illegible.
>
> ---
>
>I want to re-work the zoom-in feature anyway (scaling is based on the shrunk version of the image and looks way worse than it should, but I did not find a perfect solution yet), so I'll keep your suggestion in mind for that!

<br>

So there are two issues:
- **Size of zoomed images can still be too small**
- **Quality of zoomed image can be bad**

Regarding the first:
Instead having a fixed zoom multiplier or a fixed zoom width... could it be something dynamically according to your resolution (or even better DPI)? Like a percentage value?

**Comment by Senryoku** [comment]
I toyed with this a little bit, but also realized that the quality problem is only relevant on Firefox. Chromium based browsers just handle downsampling way better, it's a basically non-issue on Chrome or Edge.
We can still improve the quality of the zoomed version in Firefox by getting rid of the scaling and relying on a width change instead, but I haven't found a clean way to do it yet (one that preserve the transition and doesn't mess with the layout).

**Comment by tooomm** [comment]
This really is an issue on Firefox:
![scaling](https://user-images.githubusercontent.com/9874850/108623661-6a97e300-7440-11eb-864c-19a0266e3038.png)

**Comment by Senryoku** [comment]
After testing a - lot - of things, this is what I think is the best compromise: #273
