### ISSUE TITLE
Sort collapsed sideboard

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#165]
The card ordering of the collapsed sideboard next to the deck should also reflect which sorting is selected for the main deck I guess? Instead it orders always by time. Cards added last stack on top.
If the sideboard is displayed below the deck, card ordering is mirrored from the deck already.

I preferred the default sideboard on top btw, even though I only run on Full HD and use several columns. :)

**Comment by tooomm** [comment]
To add to the above.... I always felt that the `\/` for "maximize" and `>` for "minimize" icons are both not ideal to move the sideboard.

In comparison, MTGA uses more intuitive layout icons which visualize better what they do:
![sb-below](https://user-images.githubusercontent.com/9874850/97122040-12b3ce80-1723-11eb-92e4-aa89ca013eea.png) ![sb-right](https://user-images.githubusercontent.com/9874850/97122041-12b3ce80-1723-11eb-9dc4-0fe208a74a73.png)

**Comment by Senryoku** [comment]
Not sure about sorting, filling it this way give a clear feedback, but I have no strong feeling about this.

I prefer the sideboard on top by default too, but sideboard on the bottom being the "safer" option (meaning it will work even on small resolutions), I think it make sense as the default.

Font Awesome also has these icons:
![image](https://user-images.githubusercontent.com/1338143/97122279-029cee80-1725-11eb-9034-646f8866e825.png)
Do you prefer those? Or other suggestion?

**Comment by tooomm** [comment]
What about these "pairs"? First two might work best:
- `window-maximize` & `columns`
- `expand-alt` & `compress-alt`
- `search-plus` & `search-minus`

**Comment by Senryoku** [comment]
I completely missed `columns`, I like those! e0ec976c98ad20816d8167ff68dbb596d53e8533
