### ISSUE TITLE
Show tooltips only after short delay

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#166]
If you move your mouse around on the page - depending on where you are - there are constantly things popping up which can be confusing and distracting.

Having a 0.5s or 1s delay before showing them on mouse hover would reduce the noise a lot. That's the normal behavior for such labels/hints/explanations I guess.

**Comment by Senryoku** [comment]
I originally used the title attribute for these tooltips, but barely anyone noticed them because of the delay. I switched to a JS library specifically to remove it and make them obvious.

**Comment by tooomm** [comment]
Look at the GitHub page for example. Right in this issue, if you hover over your name or the `Owner` tag, none of them shows right away. And they don't disturb you while you move around on the site normally.

**Comment by Senryoku** [comment]
Added a 250ms delay to the tooltips c20eaf4db7e0c61cfb22a526b6761001c5cd149e
Not sure if you'll find this delay long enough, but it should reduce the visual noise somewhat while staying easily discoverable.

**Comment by tooomm** [comment]
That doesn't sound much. But we will see! :)
