### ISSUE TITLE
Allow multiple picks

### ISSUE THREAD

**Issue by Senryoku** [Senryoku/MTGADraft#168]
Add an option for 2 or more picks per pack. Need to wait for #163 to be merged.
Useful for Cube or, for example, Commander Legends (2 cards per pack).

**Comment by tooomm** [comment]
The recent set Double Masters had a double pick as well, but only for the first pack/pick.

**Comment by Senryoku** [comment]
Implemented in 87a718bd6b70ebba8449b9b697fc8fdaf82263fc
No plans to add the special rule for Double Masters for now.
