### ISSUE TITLE
Deck building: hide land options behind drop down

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#171]
The land options take up super much space and clutter the interface a lot, even though the users only needs them once at the very end in most cases.

This is only a short reminder ticket after talking with @Senryoku in detail.

**Comment by tooomm** [comment]
#173 turned out great!

Related notes:
- While drafting (and not yet in deck building phase), the new `Deck (x + y)` count is visible all the time and counts already down from 40 showing `Deck (1 + 39)` after your first pick. :)
Should just be `Deck (x)` during drafting.
- Actually, the `Export` buttons are also not needed during an ongoing draft. Same as the `Share` button already is only available starting in deck construction and not drafting itself.
- I also noted that the basic count is not correctly cleared after cancelling and restarting a draft

**Comment by Senryoku** [comment]
>     * While drafting (and not yet in deck building phase), the new `Deck (x + y)` count is visible all the time and counts already down from 40 showing `Deck (1 + 39)` after your first pick. :)
>       Should just be `Deck (x)` during drafting.

Good catch, fixed! b190055f12c325288e0f1acb3b09f8223726aa52

>     * Actually, the `Export` buttons are also not needed during an ongoing draft. Same as the `Share` button already is only available starting in deck construction and not drafting itself.

They're always here as a "fail safe", if something goes wrong during the draft you can still export your picks.

>     * I also noted that the basic count is not correctly cleared after cancelling and restarting a draft

Fixed! c824a067d6d289f0a0cac8494730850c9d03e365
