### ISSUE TITLE
Easier navigation in Draft logs

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#174]
Picks are constantly counted up from the first card you are picking to the very last in all draft instead utilizing the pack information. That makes it more difficult to orientate and navigate in the logs.

On top of that it would be awesome to have jump marks to go to the start of pack 3 right away for example.

**Comment by Senryoku** [comment]
Updated the notation in 3570047fbe904e45bd047b860a3392733f98b283

I'd like to improve the navigation too, but I'm not sure what's the best approach here. Should I remove the scrolling entirely and display only one pick at a time? (Using dropdowns/arrows for navigation, like in the spectator view)

**Comment by tooomm** [comment]
>I'd like to improve the navigation too, but I'm not sure what's the best approach here. Should I remove the scrolling entirely and display only one pick at a time? (Using dropdowns/arrows for navigation, like in the spectator view)

I just had the chance to review the spectator view. Yeah, that's cool! It's a good match for the draft logs as well.
There is still the MagicProTools link one click away for the scrolling view. :)

<br>

>Picks are constantly counted up from the first card you are picking to the very last in all draft instead utilizing the pack information.

That is also the case in the spectator view:
![nopacks](https://user-images.githubusercontent.com/9874850/128547419-76dac639-a83c-45df-96c8-ffb4d9577e8c.png)

Instead `Pack #2, Pick #1` with individual dropdowns and arrows each, it only shows `Pick #15`.

**Comment by Senryoku** [comment]
> That is also the case in the spectator view:
> ![nopacks](https://user-images.githubusercontent.com/9874850/128547419-76dac639-a83c-45df-96c8-ffb4d9577e8c.png)
> 
> Instead `Pack #2, Pick #1` with individual dropdowns and arrows each for easy navigation, it only shows `Pick #15`.

Updated in 6c6aaf3721e28050652bbfbb0da551070c5c6771
![image](https://user-images.githubusercontent.com/1338143/128797842-2021e390-b888-4cd8-9380-f63e78b2f47f.png)

**Comment by Senryoku** [comment]
1713b19c9c59217cd8c6c2a9ac8c256da12e7f58 brings the same navigation style to standard draft logs.
