### ISSUE TITLE
Deck building: Highlight applied sorting option

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#176]
One can sort the cards by cmc, type etc. during drafting and deckbuilding.

Before, there was a sort button which collapsed and offered the various options to choose from. I think it always showed the selected one and hid the other options.

Now that all options are constantly visible (which I'm not sure is ideal to begin with), the user can not tell by looking at the options which sorting pattern is applied.
The selected and currently active sorting option should be highlighted at least. There is already a hover effect, something along that lines maybe?

<br>

Also, two other related, minor things:
- The black color bar in the sorting by color option is not very well visible - maybe use "Plains" instead "Swamp" color?
- I think a gap between the group of column options (+/-) and the group of sorting options (cmc, color, rarity...) would be helpful as well

**Comment by Senryoku** [comment]
> Before, there was a sort button which collapsed and offered the various options to choose from. I think it always showed the selected one and hid the other options.

It didn't: There's no concept of "current sorting option" right now, this is something I want to fix while working on #157
I'm closing this issue and adding these suggestions to #157

**Comment by tooomm** [comment]
Ok, that makes sense!

<br>

>Before, there was a sort button which collapsed and offered the various options to choose from. I think it always showed the selected one and hid the other options.

The second part might not be true, I don't recall exactly.
But the sorting options were combined in the white "sort by cmc" button at one point pretty sure?

**Comment by Senryoku** [comment]
Yes, they were just hidden until mouse hover
