### ISSUE TITLE
Tooltip reappearing after a Swal is closed

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#177]
After starting a game, the tooltip explaining the game mode reappears when the game starts.

- Hover over game type button
- Tooltip with hint is shown
- Click button
- Tooltip disapears
- (Depending on the game type some launch options might be shown and needs approval)
- Hint that the draft is starting or cards for sealed are distributed is shown
- Game starts
- Tooltip reappears

![Untitled](https://user-images.githubusercontent.com/9874850/98677317-27b47280-235d-11eb-823b-f7bed4774ae7.png)

![Untitled2](https://user-images.githubusercontent.com/9874850/98677621-8c6fcd00-235d-11eb-9978-685ec19dccd7.png)

**Comment by Senryoku** [comment]
I guess this is the normal behavior of [v-tooltip](https://github.com/Akryum/v-tooltip) as the element regain focus when the modal is closed. Not sure how to fix this.

**Comment by tooomm** [comment]
True, it's not only on game start!
If you cancel the dialog that asks you how many boosters every player should receive for a sealed game... the same happens.

**Comment by Senryoku** [comment]
Finally found a fix. Solved in ff7d60f.
