### ISSUE TITLE
Starting a normal draft can start a burn draft

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#178]
- Start a glimpse/burn draft
- Stop it
- Start a normal draft
- Another glimpse/burn draft is started because the `burn cards` option (set when starting a glimpse/burn draft) is preserved

Probably a side effect of how things work and the "shortcut" implemented in the `Other Game Modes` menu.

**Comment by Senryoku** [comment]
> Probably a side effect of how things work and the "shortcut" implemented in the `Other game modes` menu.

That's exactly it. I knew about the limitation but am kind of hoping that no one will hit this case in normal use :D

**Comment by tooomm** [comment]
As you are aware of it... and it should only happen in rare occasions... :)

Feel free to close this as a no fix for now to keep the tracker more clear.

**Comment by tooomm** [comment]
Hmm, as I realized one can not start the more special game modes like "Rochester" or "Grid" draft with bots.
In comparison, Glimpse/Burn draft is allowed to start with bots.

However, bots only pick cards and do not burn cards... so it's basically broken with bots and makes no sense.
I'm posting this here as Glimpse/Burn might need its own treatment in order to avoid these problems.
As glimpse/burn draft is handled as regular draft, they also offer to replace dropped players with bots which makes no sense if they are not supported. Rochester and Grid do not offer that for example.

**Comment by tooomm** [comment]
What about this... if a draft is done, the "number of cards to burn from each booster" setting is reset to defaults. That way the `Draft` button has it's normal expected behavior again and the additional Glimpse/Burn button still sets the desired custom value on start.
