### ISSUE TITLE
Uncaught TypeError: data.flat(...) is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by aloisdg** [Senryoku/MTGADraft#18]
Hello,

I cam across a strange behavior. Steps to reproduce:

* Open mtgadraft
* New sealed game with bots
* Valid popup
* Wait...

![image](https://user-images.githubusercontent.com/3449303/79057722-b694cb80-7c64-11ea-8754-790af00825a6.png)

The snippet in question:

![image](https://user-images.githubusercontent.com/3449303/79057728-d1ffd680-7c64-11ea-985f-e17a679e6e25.png)

data is:

` ` `json
[["71091","71089","71305","71278","71092","71166","71324","71156","71111","71068","71182","71236","71070","71187"],["71078","71273","71157","71109","71111","71163","71148","71106","71146","71073","71236","71198","71117","71098"],["71274","71305","71102","71193","71169","71072","71198","71129","71224","71135","71167","71146","71243","71087"],["71134","71085","71128","71231","71106","71183","71071","71136","71239","71165","71216","71186","71232","71098"],["71301","71285","71297","71115","71190","71227","71170","71205","71121","71076","71150","71182","71322","71112"],["71134","71241","71099","71218","71239","71197","71069","71104","71144","71216","71204","71201","71165","71123"]]
` ` 

What is the purpose of `flat()`?

**Comment by Senryoku** [comment]
I can't reproduce the issue. This is Chrome right?
The purpose of flat (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) is to turn the Array of Array of IDs into a flat Array of IDs.

**Comment by Senryoku** [comment]
I think you error is related to your pull request, probably the isEmpty change.

**Comment by aloisdg** [comment]
@Senryoku the error is in the deployed website. Thank you for the MDN link. I didnt know that we had a flatten function in js. neet :)

**Comment by Senryoku** [comment]
Uh, that's weird, still can't reproduce. And data is an array, as it should be.
(The bots option should do nothing for sealed btw, does it happen regardless of its value?)

**Comment by aloisdg** [comment]
I debug alone with 1 or 2 bots.

**Comment by aloisdg** [comment]
I cant reproduce it right now.
