### ISSUE TITLE
New non-mtga card pool: missing sets + ordering

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#181]
- Introductory sets missing, e.g. Portal
- Masters Editions "I" missing
- Ordering of Un-sets and Masters wrong (oldest first instead newest first)

**Comment by Senryoku** [comment]
Fix order in 5931ff7c194d42c79fe7d770090da7148f39a9ba
![image](https://user-images.githubusercontent.com/1338143/98706475-2bf18780-237f-11eb-884c-53a5214223ea.png)

I left the Starter products out intentionally as I don't think they're intended to be draftable (I guess that's debatable for other sets too, like Unsanctioned). Their cards should still be available for cube. Do you think they should be in there?

**Comment by tooomm** [comment]
Thanks for adding ME1 and fixing the ordering already (and Rochester, and...) 👍 

Maybe there is a pattern or group of sets that you always want to exclude and just add all the others?
What set types does your card source provide? Probably you want to go from there and don't want to manually maintain that list all the time by hand?

**Comment by Senryoku** [comment]
Most non-draftable sets are filtered from this list by the import python script, their cards are still available for cubes. I'll iterate on it if I get specific requests.
Maintaining the displayed categories manually should be okay, it's not like there's a new master set every month.
