### ISSUE TITLE
Feature request: Show pod seat count in Title element

### ISSUE THREAD

**Issue by joesaraceno** [Senryoku/MTGADraft#189]
It would be nice to be able to see the player count in the MTGA Draft browser tab. This way when multitasking (waiting for a table to fill), there is good visual feedback of the current player count. 

Bonus points for friendly notifications on the title bar when a player enters, leaves, or when a table fills.

**Comment by Senryoku** [comment]
That's a great idea! Working on it :)

Is this join notification friendly enough? 😃 
![image](https://user-images.githubusercontent.com/1338143/103491889-819a5b80-4e27-11eb-9504-81614fdc0e85.png)

**Comment by joesaraceno** [comment]
Looking good! Although it may not be the best a11y, perhaps you could utilize color for some quick ui feedback - table with only 1-4 players is red, 5-7 is yellow, and 8/8 is green.

**Comment by Senryoku** [comment]
Do you mean changing the text color? I don't think this is possible, emojis are already only possible thanks to the extensiveness of unicode :)

**Comment by joesaraceno** [comment]
I was thinking to eschew the emoji idea and maybe just use a round stoplight-esque icons. Splitting something like this out into the different dots and rendering the appropriate one, perhaps flashing when change states. https://www.pngkit.com/view/u2q8u2u2t4e6e6w7_horizontal-traffic-light-icon/

**Comment by Senryoku** [comment]
I feel like the text should be enough to indicate the current status. Doesn't look like there are such icons in unicode anyway.
Emojis are only used momentarily in notifications to draw attention to an event.
