### ISSUE TITLE
Multiselect for Set(s) should use modifier keys for picking multiple sets

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#196]
Right now if I open the app and then click ZNR (most likely because I want to draft ZNR) I end up with ZNR+KLD, which I find a little surprising and confusing, and then it takes a minute to realize that you have to click KLD to remove it and get just ZNR. I think left-clicking a set should unselect all other sets in favor of drafting just that one set, and ctrl-click and shift-click (or perhaps a different interface option I haven't considered) should allow for the more complex and less common workflow of selecting multiple sets for a draft.

**Comment by Senryoku** [comment]
The library I use for the multiselect doesn't support this sadly (and I don't think the provided event hooks are enough to hack it on top of it ourselves).

In any case, even if I would also prefer this behavior personally, the current one has the benefice of teaching new users that selecting multiple sets is a possibility. I don't know if this is that valuable, and I get that deselecting the sets you don't want is slightly annoying, but after debating multiple times if I should get rid of this multiselect altogether, I still think the current solution isn't too bad.
