### ISSUE TITLE
Show shared decks in read-only bracket

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#197]
I think when people are drafting KHM before its release in the app it might be really nice for folks to be able to see decks even if they weren't in the draft. It's also a little surprising that this isn't available as a user when the read-only bracket feels like it should have roughly the same info that a player sees.

**Comment by Senryoku** [comment]
Surprising indeed, I must have moved things and forgot to re-wire everything correctly!
Should be fixed with ffa66d04d56d05970833f43cccdee46930414738 (Draft log wasn't requested as initially intended)

**Comment by wrmacrae** [comment]
This is fixed (and awesome) thanks!
