### ISSUE TITLE
Trophy icons don't show up always

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#199]
<img width="1129" alt="Screen Shot 2021-01-15 at 1 44 14 PM" src="https://user-images.githubusercontent.com/2793499/104782571-46f2c600-5739-11eb-817f-00992c337c0c.png">

This is a bug that I can investigate further

**Comment by Senryoku** [comment]
Hopefully fixed by 6ad66a842a6e088a8706e1bc4ca63aa675437de6

**Comment by wrmacrae** [comment]
Seems fixed to me! Thanks
