### ISSUE TITLE
Land distribution for IKO

### ISSUE THREAD

**Issue by nebanche** [Senryoku/MTGADraft#20]
I've been loving the app and using it a lot with friends, but noticed how the gainlands are handled is a bit odd.

Maro has reported its a 50% chance to have the land be one of these gainlands

I'm happy to make a PR for this, but can you help point in the direction where I could find this part of the code?

**Comment by Senryoku** [comment]
I want to have a more generic solution for this.
When a single set is selected we should add a proper land slot with a specific handler which implements rules for sets with common non-basic lands.
I'm not certain what's the best approach, but most of the logic should be in Session.generateBoosters and the specific method for each set. I'll give it a go right now.

**Comment by Senryoku** [comment]
Added Ikoria land rules in this commit deb12a5bbd91f3978366cad3be406919a95afcd4 , working on other rules now. Sorry, about the diff noise, the only relevant part in Session.js is in generateBoosters starting at line 306.
