### ISSUE TITLE
Switching between players in draft log doesn't switch shared decks

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#204]
Bug: in the draft log view if multiple players have submitted decks and you use the dropdown to see one player's deck, the card piles don't update when clicking on a different player to show the deck they shared. Everything else seems to update okay above the piles (name, basics, etc.) As a workaround, you can get the correct deck by changing the dropdown to Cards and then back to Deck (h/t Ben Werne for identifying the bug and the workaround).

**Comment by wrmacrae** [comment]
![image](https://user-images.githubusercontent.com/2793499/105260393-99b9ec80-5b42-11eb-84dc-9c924e229248.png)

**Comment by Senryoku** [comment]
A little janky, but this should fix it c7637df38a2de4de12e4da80d92956b85090a979

**Comment by wrmacrae** [comment]
Fix confirmed locally
