### ISSUE TITLE
Cap boosters per player at 100ish

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#205]
Minor nit: we should probably have a maximum on the boosters per player field in the UI, since it causes the options modal to grow without bound and eventually crashes the tab in the browser if you set it too high. I did this inadvertently because  I was trying to type "1" and my MacBook has really bad butterfly keys that stick sometimes. Users should know not to do this anyway, but given that it crashes the frontend, I think it's worth defending against if that's an easy change.

**Comment by Senryoku** [comment]
You're right, there was a limit already but browsers do not prevent users from entering out-of-bounds values entirely.
e6d93077fcd5e025504800da819e22d088d5ace0 should fix this.
