### ISSUE TITLE
Link to brackets if pod is full

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#206]
I think it would help if the modal when you try to join a full pod (https://github.com/Senryoku/MTGADraft/blob/master/server.js#L820) also had a link to the read-only bracket for that pod. People don't link to read-only brackets that often, but usually the original link to a pod remains available (on discord, twitch chat, etc.) to people beyond the first 8 players. If we kicked them over to a spectator-type experience, or just gave them an option for that before starting a new pod, I think it would help for people to follow along with a pod that they're not playing in. This would go especially well with #198 , but even just being able to see decks people build for KHM right now, and being able to see live match results in the team draft showdown this week (if they bother to put them in the bracket this time, grrr) would be really valuable!

**Comment by Senryoku** [comment]
Yep, this will be important to remember if we do add a spectator mode.
I've added a link to bracket with a10fd5ade69eefb65290c89a6fdc2604566dd312 so I'm closing this issue and will add a note in the spectator mode discussion.
