### ISSUE TITLE
No footer on Firefox (Windows)

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#208]
I still run 84.0.2 on Windows 10 64bit.

When accessing from new Edge browser (Chromium based) it displays all fine.

**Comment by Senryoku** [comment]
Weird, it's correctly displayed on both Firefox 84.0.2 and 85 here

**Comment by tooomm** [comment]
Today it displays again. Must have been an issue on my end!

Sorry for the noise.
