### ISSUE TITLE
Team Sealed support

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#210]
I would love to play some Team Sealed with my friends!
It was the most fun competitive team format out there officially supported by Wizards IMO. At Grand Prix level (now Magic Fest), the Team Limited events are Team Sealed on Day 1 and Team Sealed + Team Draft on Day 2.

Hints:
- It's played in 3 person teams (like 3v3 Team Draft)
- Every team opens 12 booster and uses them as a shared card pool for all 3 player to build the decks
- Every card needs to be assigned to one person and his deck or sideboard
- 3 dedicated decks with sideboards must be build

<br>

The difficult part is how deck building should be done because all players of a team share the same single card pool. Cards can obviously just be used once, you need to decide which player gets which one.

I assume it's not really possible or practical to let all 3 team members edit everything at the same time and move cards around simultaneously.
- One idea is that players request cards (or simply pull?) from the shared card pool of their team to transfer them in their own pool and build their decks.
- The other is that there is a "captain" in every team that builds the 3 decks for his team and the others can only view and give hints/suggestions and download the deck lists at the end.
That's also how many experienced players do this in paper to streamline ideas, don't get lost in discussions and manage the time pressure during competitive deck building best.
- Other ideas?

**Comment by Senryoku** [comment]
I've never seen this format before, I'm not sure there's a real demand. 
This looks like it would need a completely different UI for a fringe use case? It could be better than screen sharing (specific UI) or list sharing (makes sure a card doesn't end up to two decks) but not by a wide margin imho.
Each captain getting the entire pool and others importing it is generally better in my eyes as everyone can experiment separately, only downside is the need to make sure each card is only used once, but I'd wager it's a mild inconvenience at worse.

**Comment by tooomm** [comment]
>I've never seen this format before

You missed a lot then. :P

From https://mtg.fandom.com/wiki/Team_events:
"Team Limited events have been a part of the professional scene since the 1999–00 season. Pro Tours featuring the format were held every year from 1999 to 2005, and Grand Prix from 2000 to 2005, and again from 2012 and on."

Team Sealed got also played in World Magic Cup and Team World Championship. The events stopped with MTG Arena.

The official Wizards site, as well as Channel Fireball both have it listed, obviously there are no events happening currently:
https://magic.wizards.com/en/content/grand-prix-event-types-events and https://www.cfbevents.com/factsheet

I remember that on many big non-team events, there often was a Sideevent options for Team Limited as well.

<br>
(I updated my initial post a bit for clarity.)
