### ISSUE TITLE
Collection stats displays some uncraftable cards

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#211]
It just makes no sense to show cards from pre-MTGA era :)

![all collection](https://user-images.githubusercontent.com/9874850/107291490-8d052600-6a68-11eb-8e11-4094d52bdf1d.png)

**Comment by Senryoku** [comment]
Looks like all these cards are in the MTGA client (i.e. they have an Arena ID), but some are indeed not craftable. Not sure how to exclude those, there's nothing in MTGA data setting them apart.

**Comment by tooomm** [comment]
Was there some kind of older cube playable at some point maybe?
The cards from such events got never added to your collection though.

>Not sure how to exclude those, there's nothing in MTGA data setting them apart.

There is not `Set` or `Date` information?

**Comment by Senryoku** [comment]
> Was there some kind of older cube playable at some point maybe?
> The cards from such events got never added to your collection though.

Probably

> There is no `Set` or `Date` information?

Here is the MTGA entry for Dragon Tyrant for example, which is not craftable:
```
{
    "grpid": 18736,
    "titleId": 30845,
    "artId": 48132,
    "isToken": false,
    "isPrimaryCard": true,
    "artSize": 0,
    "power": "6",
    "toughness": "6",
    "flavorId": 1,
    "collectorNumber": "88",
    "collectorMax": "143",
    "altDeckLimit": null,
    "cmc": 10,
    "rarity": 4,
    "artistCredit": "Kev Walker",
    "set": "SCG",
    "linkedFaceType": 0,
    "types": [
      2
    ],
    "subtypes": [
      21
    ],
    "supertypes": [],
    "cardTypeTextId": 8,
    "subtypeTextId": 1318,
    "colors": [
      4
    ],
    "frameColors": [
      4
    ],
    "frameDetails": [],
    "colorIdentity": [
      4
    ],
    "abilities": [
      {
        "abilityId": 8,
        "textId": 46
      },
      {
        "abilityId": 14,
        "textId": 28
      },
      {
        "abilityId": 3,
        "textId": 22
      },
      {
        "abilityId": 97022,
        "textId": 312028
      },
      {
        "abilityId": 1097,
        "textId": 312029
      }
    ],
    "hiddenAbilities": [],
    "linkedFaces": [],
    "castingcost": "o8oRoR",
    "knownSupportedStyles": [],
    "DigitalReleaseSet": "",
    "abilityIdToLinkedTokenGrpId": []
  }
```

and for Captain Sissay which is craftable:

```
{
    "grpid": 14717,
    "titleId": 16473,
    "artId": 25145,
    "isToken": false,
    "isPrimaryCard": true,
    "artSize": 0,
    "power": "2",
    "toughness": "2",
    "flavorId": 16474,
    "collectorNumber": "237",
    "collectorMax": "350",
    "altDeckLimit": null,
    "cmc": 4,
    "rarity": 4,
    "artistCredit": "Ray Lago",
    "set": "INV",
    "linkedFaceType": 0,
    "types": [
      2
    ],
    "subtypes": [
      39,
      64
    ],
    "supertypes": [
      2
    ],
    "cardTypeTextId": 261554,
    "subtypeTextId": 50231,
    "colors": [
      5,
      1
    ],
    "frameColors": [
      5,
      1
    ],
    "frameDetails": [],
    "colorIdentity": [
      5,
      1
    ],
    "abilities": [
      {
        "abilityId": 6371,
        "textId": 16475
      }
    ],
    "hiddenAbilities": [],
    "linkedFaces": [],
    "castingcost": "o2oGoW",
    "knownSupportedStyles": [
      "DA"
    ],
    "DigitalReleaseSet": "AHA1",
    "abilityIdToLinkedTokenGrpId": []
  }
```

The set property isn't enough because of Historic Anthologies, but maybe I can check for the DigitalReleaseSet when "set" is older than Ixalan. I'll have to triple check to make sure there's no weird exceptions.

**Comment by Senryoku** [comment]
> The set property isn't enough because of Historic Anthologies, but maybe I can check for the DigitalReleaseSet when "set" is older than Ixalan. I'll have to triple check to make sure there's no weird exceptions.

Nope, this approach won't work, there are cards that were digitally released outside of these Digital only sets (like Hanna, Ship's Navigator:)

```
  {
    "grpid": 48499,
    "titleId": 16782,
    "artId": 25472,
    "isToken": false,
    "isPrimaryCard": true,
    "artSize": 0,
    "power": "1",
    "toughness": "2",
    "flavorId": 16783,
    "collectorNumber": "249",
    "collectorMax": "350",
    "altDeckLimit": null,
    "cmc": 3,
    "rarity": 4,
    "artistCredit": "Dave Dorman",
    "set": "INV",
    "linkedFaceType": 0,
    "types": [
      2
    ],
    "subtypes": [
      39,
      4
    ],
    "supertypes": [
      2
    ],
    "cardTypeTextId": 261554,
    "subtypeTextId": 261697,
    "colors": [
      1,
      2
    ],
    "frameColors": [
      1,
      2
    ],
    "frameDetails": [],
    "colorIdentity": [
      1,
      2
    ],
    "abilities": [
      {
        "abilityId": 10712,
        "textId": 16784
      }
    ],
    "hiddenAbilities": [],
    "linkedFaces": [],
    "castingcost": "o1oWoU",
    "knownSupportedStyles": [
      "DA"
    ],
    "DigitalReleaseSet": "",
    "abilityIdToLinkedTokenGrpId": []
  }
```

Scryfall has a `games` property but it's not 100% reliable (Hanna from Invasion isn't listed as playable on MTGA for example, but only the PANA (https://scryfall.com/sets/pana) version which doesn't exists in game at all). 

Honestly at this point I'm kinda ok with the Collection panel being slightly wrong in the "Other" category to avoid any other problem.
Maybe just manually exclude these cards from the panel? There's not a lot of them, right?

**Comment by tooomm** [comment]
How do you craft such cards like Captain Sissay?
I'm only aware of adding cards to your collection via opening boosters (in limited games or just for fun).

Thanks for investigating @Senryoku.

>Honestly at this point I'm kinda ok with the Collection panel being slightly wrong in the "Other" category to avoid any other problem.

You are probably right... there can be an informative hint once a user selects `All` or `Other Sets`.

>Maybe just manually exclude these cards from the panel? There's not a lot of them, right?

I've no clue how many there are!
