### ISSUE TITLE
Improve set drop down for sealed

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#213]
Since https://github.com/Senryoku/MTGADraft/commit/08f4dd522a66dc84917dc342e3430878ac56aedd, there are drop downs in the sealed modal for set selection:
![modal](https://user-images.githubusercontent.com/9874850/107291638-c6d62c80-6a68-11eb-8f72-8ddeb7e28165.png)

They are kinda big and clunky, which makes them unnecessary difficult to use and navigate within them.

It would be great if they look and behave like the ones in `Settings`, which are smaller and sharper.
They also have a better structure of the available options.
![settings](https://user-images.githubusercontent.com/9874850/107291630-c473d280-6a68-11eb-8869-a51f62738969.png)

**Comment by Senryoku** [comment]
15d2443859d3b85df1ff4118508a4fc0337bfb4a made it more consistent
![image](https://user-images.githubusercontent.com/1338143/107552780-3ddc0400-6bd4-11eb-995a-7673d7ace547.png)

**Comment by tooomm** [comment]
That looks waaay better! Can't wait to try it live. 😍

**Comment by tooomm** [comment]
Missed it in your screen at first...

Ordering is not `newest first` yet as in all other drop downs:
![upside down](https://user-images.githubusercontent.com/9874850/107873617-188d1580-6eb4-11eb-9a91-f7f4c1514d0b.png)

Besides that it's great!

**Comment by Senryoku** [comment]
511ca0bd3f17faac1bfd5881d3f047682773c269
