### ISSUE TITLE
Highlight own name in app

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#215]
This is mostly useful for other people watching you.

Highlighting your own name in the list of players and game logs would be very useful to quickly identify the point of view, whom they are passing to etc. when you watch other players in streams, discord share or other videos for example.
Not everybody uses the same nick on all services or some streamers might cut the view down to exclude the settings on top with their user name etc.

**Comment by Senryoku** [comment]
Something like that? 
![image](https://user-images.githubusercontent.com/1338143/108468885-afc4e500-7287-11eb-943d-eba20b1e14d0.png)

**Comment by tooomm** [comment]
I need to check this live with more context of all page, but that looks very promising. You managed to find a subtle solution! 👍 

>didn't apply this to the draft logs as userIDs can change over time.

What do you mean? If somebody changes his username... would that mess with old logs where your nick was different? 
I was hoping to see this in logs as well. 🙈

**Comment by tooomm** [comment]
This is also very important to have during a draft, not only in the pre-game!
![name](https://user-images.githubusercontent.com/9874850/108854921-b1c0d800-75e8-11eb-8fcf-4ddc121fe7b8.png)

**Comment by Senryoku** [comment]
Mmh, yes... I knew code duplication would get me eventually 🙄 
Should be fixed with a0babf97208b054f5bea573c9343094e362e8f99

**Comment by tooomm** [comment]
>Should be fixed

Yess! 👍 
![highlight](https://user-images.githubusercontent.com/9874850/109419427-b2cd7d00-79cd-11eb-9afa-6289ad3d8392.png)

I would still find it very useful to have it work the same way in logs...
![nohighlight](https://user-images.githubusercontent.com/9874850/109420078-e3fb7c80-79d0-11eb-982c-3caee30c876e.png)

**Comment by Senryoku** [comment]
8fe20942bad32df4e5ece9181e5231e8e0930446 implements self-highlighting in draft logs when possible.
