### ISSUE TITLE
Card list import modal doesn't close on successful import

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#216]
After pasting a sealed deck pool from 17lands to play around with it, I hit `Import` and got the `Successful` message.

The pool loaded but the import dialog stayed open:
![import](https://user-images.githubusercontent.com/9874850/108127044-eb568800-70aa-11eb-8391-b376c0f9e3d9.png)

**Comment by Senryoku** [comment]
39cb45d3a2a4bca6ff0041dfbc381816c988f1fc
