### ISSUE TITLE
Improvements to hashes

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#218]
- Hashes should have a tooltip that clicking them copies to clipboard. Just like the log path location. 👍 
- Magic Workstation seems to be super outdated and unmaintained. Not sure people still use it? Especially for competitive play where the hash is useful...
The official websites is not updated in years and the news even say the most recent cards should be from Ixalan. :)
Probably save to remove it?

**Comment by Senryoku** [comment]
Is there really a reason to copy the hashes? Don't you compare them visually usually?

Yeah, MWS seems pretty outdated, I even had a lot of trouble just setting it up to test the implementation. I'm concerned that the hashes are actually broken and I can't test them reliably, but other than that, is there really a reason to get rid of it?

**Comment by tooomm** [comment]
> I'm concerned that the hashes are actually broken and I can't test them reliably

If you can't be sure something sensible like a hash is correct, that alone is probably a strong argument against it. There is no use for a hash that might not work correctly all the time.

But yeah, I'm always a fan of clean and intuitive interfaces. MWS looks like dead software, why support it?
I mean, if people really miss it you can revert the removal commit. Or only comment it out for now. :)

**Comment by Senryoku** [comment]
For reference this is the updated card list I found last time: https://www.slightlymagic.net/forum/viewtopic.php?f=38&t=29507

But, yeah, quickly surveying the web mostly unearthed some "Is MWS dead?" threads from years ago ^^"
Sooo... I'll keep the hashes for now but they'll be the first thing to go if we need to reclaim some space.

**Comment by tooomm** [comment]
Thanks for the link!
Quite interesting to read... they refer to the "new 0.94f version" when they speak of the `11 Aug 2005` release. 🙈
Can't believe you have to pay for the software.

>I'll keep the hashes for now but they'll be the first thing to go if we need to reclaim some space.

Fair enough.
