### ISSUE TITLE
Better favicon support

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#219]
Improve quality and support modern types, like shortcuts on different systems.

This is an example of the firefox `Top Sites` area with scryfall having proper support:
![Untitled](https://user-images.githubusercontent.com/9874850/108360233-3aa6d080-71f1-11eb-96f5-cd70d85a4699.png)
MTGADraft only uses a cropped screenshot of the page and scales the tiny favicon.

https://realfavicongenerator.net/ could be useful. It also tests your current one.
Do you have a svg source?

**Comment by Senryoku** [comment]
> Do you have a svg source?

No, it's a raster image made in Glimpse.
Thanks for the link, it's interesting. We'll need a proper logo (in a vector format this time!) before setting all of this though :D

**Comment by tooomm** [comment]
Jep, we could need some help here. :)

**Comment by Senryoku** [comment]
6ffd3a70adbd4ed198d69b1732d6becef0289527: The logo is still awful (I tried multiple times to come up with something better, alas I'm definitely not a graphic designer :D), but at least it's available in multiple resolutions now.

**Comment by tooomm** [comment]
Quality did improve a lot 👍 
![grafik](https://user-images.githubusercontent.com/9874850/221420716-8cc0262d-dcc0-4d92-89bf-b4732da3dbc0.png)

There is some grey background though. The only icon having that is the [apple touch one](https://github.com/Senryoku/MTGADraft/commit/6ffd3a70adbd4ed198d69b1732d6becef0289527#diff-9c876c12b6952ab17379b3f1e0db6a17fa9beb40c5809adf68d2fbc1f8899663).
Not sure why Firefox is using this one here?

**Comment by Senryoku** [comment]
Looks like it's intended: https://udn.realityripple.com/docs/Mozilla/Firefox/UI_considerations
Following these recommendations, I tried adding the source svg icon like this: `<link rel="icon" href="/logo.svg?v=3" />`, without luck.
