### ISSUE TITLE
Redirect http to https

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#221]
I realized, that you can access the page via unsecure `http`: http://mtgadraft.herokuapp.com/

**Comment by Senryoku** [comment]
Why is that a problem? You get the protocol you asked for.

**Comment by tooomm** [comment]
Not a "problem" per se. At least not yet.
The issue was mostly about raising awareness and putting a reminder up as I ran across it.

Most users probably *did not explicitly ask for http*, they just use the internet...
There are old links posted somewhere, shortcuts/bookmarks saved, auto-completion, even just habits or lack of knowledge keep users unintentionally using simple http.

https is kinda mandatory nowadays and the project supports it already. I think it's smart to redirect people in order to guide them a bit and setup for the future. There is no harm either.

In case you consider this at one point, I'll leave some helpful links here:
- https://help.heroku.com/J2R1S4T8/can-heroku-force-an-application-to-use-ssl-tls
- https://stackoverflow.com/questions/34862065/force-my-heroku-app-to-use-ssl-https
