### ISSUE TITLE
Expand further card displaying options to other layouts

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#231]
Finally managed to look into this and provide screenshots.

Double faced cards are well supported and players are able to show their back side in order to make decisions.
Many special card layouts which are now available from older sets do not yet support showing related information on their back. Others are not readable in the first place because they require manipulation of the card orientation:
- Meld (should show the resulting melded card)
- Split / Fuse (should rotate 90° clockwise)
- Aftermath (should rotate 90° counter-clockwise)
- Flip (should rotate 180°)

![3](https://user-images.githubusercontent.com/9874850/113157408-27990e80-923b-11eb-9662-5d82e380f3ff.png)
![2](https://user-images.githubusercontent.com/9874850/113157404-27007800-923b-11eb-843a-fb6e5946cace.png)
![1](https://user-images.githubusercontent.com/9874850/113157397-2667e180-923b-11eb-9fef-391e889e64dd.png)

**Comment by Senryoku** [comment]
I'll experiment with this there: https://github.com/Senryoku/MTGADraft/pull/234 (only supports flip cards right now).

Split and Aftermath cards are both labeled as "split" layout in Scryfall, we'll have to separate them somehow (Check for the extension or the "Aftermath" keyword?).
Meld aren't straightforward either (given the limited number of melding cards I'm tempted to manually list them, but it's obviously not future proof). Also, should the back be just the corresponding half (like a physical card), or the resulting melded card (more useful, and easier to implement)?

**Comment by tooomm** [comment]
>#234 should now cover all the listed use cases

The result is very nice!

While I spotted your great details with the different icons and the (partial) rotation accordingly to the movement of the card - which feels just great - I realized that the new meld, but also the old double faced cards show and rotate the icon differently than the card is actually turned face up/down:
![rotate-flip](https://user-images.githubusercontent.com/9874850/113287726-3db3d700-92ee-11eb-8802-7c9d8c8dc64d.png)

They need to display the icon/arrows and the icon animation the other way around to match the actual transition of the card.

**Comment by Senryoku** [comment]
Hahaha, true, I've reversed the card animation here: 977f128ff339cd57022620b29f0e701ebbc0732d
