### ISSUE TITLE
Mystical archive rarity distribution

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#239]
The mystical archive has a custom rarity distribution for its slot, which pack collation should reflect (67% uncommon, 26.4% rare, 6.6% mythic) according to https://magic.wizards.com/en/articles/archive/feature/collecting-strixhaven-school-mages-2021-03-25

**Comment by Senryoku** [comment]
Should be fixed with 34edd08a658c7f5d5000731f1c1985421d10ad2c

**Comment by wrmacrae** [comment]
Thanks!
