### ISSUE TITLE
Lesson rarity for Strixhaven

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#240]
Currently I think the app chooses lessons uniformly from the pool of lessons (except for mythic promotion logic). Although I cannot find a source about rarity distribution of the lessons, other collations decisions wotc has made (for example with mdfcs in ZNR, and with the mystical archive) indicates they will probably try to make the frequency that a given uncommon lesson appears in a booster similar to the frequency that a given other uncommon appears, and same for commons, rares, and mythics. Since there are 5 rares and 5 uncommons in particular, but a given non-lesson rare is almost three times as rare as a given non-lesson uncommon, we probably have to weight the lesson rarity somehow. Opening this issue for tracking, and I can revisit after doing some more math and research with a concrete suggestion about rarity distribution so that the rares don't feel too frequent.

**Comment by wrmacrae** [comment]
LoL episode 198 said the lesson slot is always common/rare/mythic, and the uncommon lessons appear as normal uncommons. Still TBD the common vs rare vs mythic rate in the lesson slot, though.

**Comment by Senryoku** [comment]
Indeed, this was pretty easy to miss...
![image](https://user-images.githubusercontent.com/1338143/113782737-f638ab00-9732-11eb-88e9-e895d150115c.png)
Does this mean you can find two lesson in a single pack? One uncommon in the uncommon slot and one in the designated and guaranteed Lesson slot? Mmh...

**Comment by Senryoku** [comment]
Tentative implementation here #244
Nor merging just yet since I'm not 100% sure I understood the booster content correctly, or if this solution makes sense :)
