### ISSUE TITLE
Set dropdown to narrow on FF

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#241]
- Chromium looks fine
![chromium](https://user-images.githubusercontent.com/9874850/113721599-f3689680-96ef-11eb-89aa-4ba30b6a98ec.png)

- Firefox too narrow
![ff](https://user-images.githubusercontent.com/9874850/113721571-ef3c7900-96ef-11eb-8bfa-0c7590bae51b.png)

**Comment by Senryoku** [comment]
0837645c3820ef4bb922ce3dda174870f57f37c7
