### ISSUE TITLE
Show vault progress in collection stats

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#251]
As opening the vault at 100% gives you wildcards it's interesting and relevant information for drafting.
Would fit well next to a wildcard count. ;)

The info is in the logs as well.

**Comment by Senryoku** [comment]
Added with 57eb8e116354b6865b8e3310838f886cee117a06
![image](https://user-images.githubusercontent.com/1338143/115048134-87e5ac80-9ed9-11eb-8631-ab19ee09dbaf.png)

**Comment by Senryoku** [comment]
And to the collection stats modal
![image](https://user-images.githubusercontent.com/1338143/115050403-017e9a00-9edc-11eb-87e9-99f2aa8731cc.png)

**Comment by tooomm** [comment]
There is a helpful tooltip for `Vault Progress`.

I think the same for the various rarities would be nice as well. Just a simple descriptive `Common Wildcards` etc.
I didn't want to mess with the loop in the table. :)
