### ISSUE TITLE
MTGA icon color

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#253]
In Windows, the app icon is white/silver instead a black `A`:
![mtga icon](https://user-images.githubusercontent.com/9874850/115145395-9951c480-a051-11eb-8ade-e20435c417b5.png)

On their page, they use a very similar light colored `A`: ![](https://images.ctfassets.net/s5n2t79q9icq/3ivtRdY55FuWSEyMPw1rR7/f8a0b75ee0e885299f20fe67f199538b/MTG_Arena_Symbol_2C_White_V14-2.png)
https://magic.wizards.com/de/mtgarena

**Comment by Senryoku** [comment]
Yep that's better d120be40902df47af442184f0a1c3f387a976e53

**Comment by tooomm** [comment]
Way better now, yes 👍
