### ISSUE TITLE
Hiding elements vs. greying out

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#255]
The UI for players (non-session owners) hides some icons that are of no use for them, e.g. `Create Bracket` and `Ready Check` ones.
Other buttons however are shown, even though they do nothing and provide no information either, e.g. the `Start a Draft` button and the `Other Game Modes` menu. They are only greyed out instead and make the area crowded and confuse people with stuff they can not interact with anyway.
That's different to e.g. the `Set(s)` dropdown, which displays fundamental information about the session for players and is shown (greyed out) for a valid reason.

**Left:** Session owner
**Right:** Session player
![non-owner-ui](https://user-images.githubusercontent.com/9874850/115147632-36195f80-a05c-11eb-8f27-b66624919b24.png)

**Comment by Senryoku** [comment]
Make sense! ed3afa0b36871450ffef26d755aac93a644fad0f
