### ISSUE TITLE
New notification icon

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#262]
Thanks for the fast implementation, it looks great, makes fun to use and saves some space!
You also fixed the jumping of icons in the panel when toggling the sound options along the lines. :)

My observations so far:
- When the user decides to block/not allow notifications for the page when trying to enable the setting, the old check box and its label got disabled to show it's not working/allowed.
The new icon is still shown and seems working as you can still toggle it, but without effect.
Could it be locked to the bell-slash one and be disabled/greyed out like the old one? 👍 <br>
**Edit:** This is only an issue on Firefox it looks like: (I can not recall 100% if it worked with FF before, or if I only saw the disabled check box in Chrome only, sorry)
![ff](https://user-images.githubusercontent.com/9874850/116710273-d9119800-a9d1-11eb-830b-f9dffac944a5.png)
On Chrome it works correctly and disables, greys out and shows the correct icon:
![chrome](https://user-images.githubusercontent.com/9874850/116710250-d31bb700-a9d1-11eb-99e7-840582753abb.png)

<br>

- Once a user blocked notifications on fault or forget about it for example, there should be a different tooltip when hovering the disabled, color changed, crossed out bell icon telling the user what's the cause to allow for a fix.
e.g. "Notifications for this domain are blocked in your browser"

**Comment by Senryoku** [comment]
Tried to improve things a little bit with 678288ce880607fa2f0d80b4f8907d971e3e8b4f
Firefox doesn't report the status correctly (stays at "default"), not sure why.

**Comment by tooomm** [comment]
Working now on Firefox as well! 👍
