### ISSUE TITLE
Add label and count to rows

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#264]
The split "table" view is missing the very useful quantity value which count the cards currently in each row.
In deck building, a player needs to worry a lot about how many creatures and non-creatures are in their deck.
As there is no support in finding that value everybody has to constantly count manually, and recount after some changes etc.

Additionally, there is no description of the rows content: `Creatures` and `Non-Creatures` / `Others`

Instead the table only having labels for the columns at the top, there should also be row labels on the left:
![row labels](https://user-images.githubusercontent.com/9874850/116874949-6ba47800-ac1a-11eb-86be-5d0637f681ec.png)

In normal "single row" view mode this labels do not need to show.

**Comment by Senryoku** [comment]
Better late than never, right? d89bf0ca1470e78b77994e4e9953e0255ec20366
![image](https://user-images.githubusercontent.com/1338143/215777704-42a786c8-2127-41df-a0dd-8a1831fc2f43.png)
