### ISSUE TITLE
The amount of cards per pack can't be adjusted

### ISSUE THREAD

**Issue by sprangg** [Senryoku/MTGADraft#282]
Adjusting the amount of cards of different rarities per pack doesn't work anymore. Been testing this relatively often for the past few weeks since I've scheduled a draft of Lorwyn/Morningtide/Shadowmoor/Eventide for tomorrow with 11-card packs, but today I noticed that packs are always 15 cards no matter how I adjust the amount of the different rarities.

Thank you for the great app and the tons of options offered by it. I'd SUPER appreciate it if this was fixable for tomorrow (within 28 hours to be exact) but I know we're all busy people and it's no huge deal. Thanks in any case!

**Comment by sprangg** [comment]
Fixed now with commit e4a869f4f539c83b1fc908e6b1ee6b5b168cb886! Huge thanks!!!

**Comment by Senryoku** [comment]
Thank you for reporting it!
I was going to respond here to let you know it was fixed but lost myself trying to fix something else hahaha
