### ISSUE TITLE
When looking at draft logs, it would be better to see your own pool by default

### ISSUE THREAD

**Issue by sprangg** [Senryoku/MTGADraft#291]
In the Game Logs -view, after pressing the review-button of a session, it would be better if it always showed your own pool first. I don't know what the current logic is, but when I look at session b7274ce2e082's logs, it shows DryTurtle's log first and not mine (Cerin).

In my opinion looking at your own log is the most likely reason to go into this view. Also when drafting among friends and not having delayed log sharing enabled, it would be nice to be able to look at your own log without first seeing someone else's drafted cards - less spoilers!

**Comment by Senryoku** [comment]
> it would be nice to be able to look at your own log without first seeing someone else's drafted cards - less spoilers!

That's a very good point. 
As discussed in #215, this won't work reliably, but we can at least try with both the userID and userName. 8fe20942bad32df4e5ece9181e5231e8e0930446 should fix both issues most of the time.

**Comment by sprangg** [comment]
Neat, thanks! We'll see how it goes.
