### ISSUE TITLE
More bots can be added than max players

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#302]
e.g. 2 humans + 7 bots (9 player) in 8 person room possible:

![bots](https://user-images.githubusercontent.com/9874850/131395090-f6f2e66f-f022-4880-85b5-8a06d3db451c.png)

Dropdown selection for bots should account for current player count and joining players.
Room size should not be able to be surpassed.
Player count in the room is not correctly counting. "(2/8)" in the example above.

**Comment by Senryoku** [comment]
That's intended, the player limit is only there to prevent additional human player to join, I don't want the bot count to interfere with that.

**Comment by tooomm** [comment]
Not so sure if that's a good intention? 🤔 

Nobody expects e.g. a 7 person game that is filled up with a bot to start as a 9 player draft just because the last person arrived last second or unnoticed, and the bot is added regardless.
The owner would probably not even care to adjust the bot setting if he happily realizes everybody arrived, just to be surprised when players complain in pack 2 (or on the wheel) that something is wrong. :)

People don't like to draft with more people than they setup the room for, especially if it's not even shown or they are not aware of this behavior. Even more so when it's >8 players and some of them are non-humans.

**Comment by Senryoku** [comment]
Consider the situation where you have 7 human players and want to complete with a single bot, with your solution you'd have to set the maximum players to 8, add a bot and potentially let another uninvited human player join. The bots could actively counts towards the maximum player count to avoid this situation, but then your example doesn't work either (the 8th wouldn't be able to join until the owner removes the bot).

I guess we could rename the setting to specify it only applies to human players, but its first function is exactly that: to prevent uninvited human player to join past the limit, and including bots doesn't help with that.

**Comment by tooomm** [comment]
> The bots could actively counts towards the maximum player count to avoid this situation, but then your example doesn't work either (the 8th wouldn't be able to join until the owner removes the bot).

I thought about it more like this:
Human players need to overrule bots of course and take their slots (replace them). Bots should not block humans from joining.
On game creation, room size - human players is the max amount of bots that get added. No matter what initial bot count is set.
