### ISSUE TITLE
Missing MID Bot Rating

### ISSUE THREAD

**Issue by Senryoku** [Senryoku/MTGADraft#308]
TODO: Add MID Bot Ratings

**Comment by tooomm** [comment]
What's your source for the bot ratings normally?

**Comment by Senryoku** [comment]
I've use Aether Hub or Justlolaman's list in the past

**Comment by Senryoku** [comment]
47ae46317418601cc82c5102465e9b0128187051

**Comment by tooomm** [comment]
>I've used Aether Hub or Justlolaman's list in the past

So you have to mix several sources and take whatever is available and comprehensive for each set, that makes sense. 👍 

Some other streamers do publish their ratings as well. I think CFB has them behind a paywall nowadays.
