### ISSUE TITLE
Seeing your own draft log

### ISSUE THREAD

**Issue by sprangg** [Senryoku/MTGADraft#321]
Currently the "Owner only, delayed" mode is great for log sharing in traditional draft tournaments where you don't know the decks of your opponents beforehand. However, it'd be useful to still be able to see your own log before the session owner unlocks all the logs. I can't think of a reason why it'd be necessary to block one from seeing their own log.

**Comment by Senryoku** [comment]
I think you have a point. 
However I feel like some might think being able to review every single pick after the fact would be too much information (Even if you could technically write them down).
What do you think about giving access only to your final card pool (useful to retrieve it easily if you leave the page), not the picks? Or were you specifically asking about the picks too?

**Comment by sprangg** [comment]
Yeah I was asking about the picks and not particularly interested in seeing the final decklist there. Our group (XDHS) usually drafts with Xmage and there your draftlog is available at all times - you can even see your in-progress log during the drafting. This has never been any issue.

I'm not asking for the log to be visible during drafting but seeing the full log right afterwards without the host unlocking everything would be nice. This could also exist as its own mode perhaps, if you don't want to change the "Owner only, delayed" mode. Something like "Personal only, delayed".

And that brings another idea to mind - in this mode it could be so that even the owner doesn't see all the logs until they unlock them. It'd remove the information-asymmetry where the session owner is able to see the logs before they're unlocked.

**Comment by Senryoku** [comment]
> And that brings another idea to mind - in this mode it could be so that even the owner doesn't see all the logs until they unlock them. It'd remove the information-asymmetry where the session owner is able to see the logs before they're unlocked. (Of course we can usually assume the host to be a trustworthy person who doesn't peek, but it'd still be a nice fair and consistent option imo.)

That's how the "Owner only, delayed" setting works :) (at least it should, file a bug if it's not the case!)

Alright, thanks for the precision, I'll see what I can do!

**Comment by tooomm** [comment]
>That's how the "Owner only, delayed" setting works :) (at least it should, file a bug if it's not the case!)

Owner = player then? I also thought owner means the room owner and game host... 🙈

**Comment by sprangg** [comment]
"Owner only, delayed" works so that nobody sees the logs until the session owner clicks a button that makes the logs visible to everyone. I just confirmed with bots. So works as intended, and good that it works this way!

I thought it didn't work this way because of some strangeness in our draft yesterday where it appeared all the logs were only visible to the owner and not the others. I'll try to find out exactly what happened and make a new issue if I figure it out. Maybe the host accidentally used the "Owner only" mode instead.

**Comment by Senryoku** [comment]
> > That's how the "Owner only, delayed" setting works :) (at least it should, file a bug if it's not the case!)
> 
> Owner = player then? I also thought owner means the room owner and game host... 🙈

Yeah, it means the session owner, I agree the name is misleading. It stems for the fact that only the owner receive the full (locked) logs so they can share them later (Logs are only stored temporarily on the server side), and also that the feature changed multiple times. I can probably rename it: Would simply "Delayed" be good enough?

**Comment by sprangg** [comment]
I agree that it's a bit misleading, part of what led me to believe that the owner was able to see the logs before the other players. Just "delayed" sounds good to me.

**Comment by tooomm** [comment]
Current state:
Send game logs to: `Everyone` / `Owner only` / `Owner only, delayed` / `No-one`
Which uses the unclear term "owner", and "delayed" might also not be self-explanatory as well. Delayed until the draft ended? Delayed for 15min?

What about:
Game logs: `Complete (everybody)` / `Complete (everybody after host approval)` / `Complete (host only)` / `Disabled`

The new options could be: `Personal (everybody)` and `Personal (everybody) + Complete (after host approval)` 


Keep in mind that ordinary users are not aware of who is owning which data in the app concept and what a session is. Those are rather technical terms and should be represented differently in the UI.

**Comment by Senryoku** [comment]
"Session owner" should be used throughout the application, I'll keep using this term.

> Keep in mind that ordinary users are not aware of who is owning which data in the app concept and what a session is. Those are rather technical terms and should be represented differently in the UI.

I agree completely, the current name is more a leftover than a conscious decision.

Your list is a little too long for my taste, I'm not sure if I want Personal to be a separate option yet.

**Comment by sprangg** [comment]
There's a tooltip that tells what the "Owner only, delayed" mode does. I agree that based simply on the name it's hard to decipher but the tooltip tells all that's needed.
![2022-05-28 13_33_55-Window](https://user-images.githubusercontent.com/13901691/170821666-42a10072-2d14-4ec9-8fd8-dc0f48da23c1.png)

**Comment by Senryoku** [comment]
I'm leaning towards these options (notice the "full" game logs):
![image](https://user-images.githubusercontent.com/1338143/170822357-96d3e577-041a-4476-a874-89db2208cfd7.png)
With this tooltip:
![image](https://user-images.githubusercontent.com/1338143/170822443-ce9f3fb0-3b2e-4fab-bcd1-895a5798b3ee.png)

Personal logs would always be accessible, even when 'No-one' is selected here.

**Comment by sprangg** [comment]
Looks great to me! And the "owner approval" mode is now named so that you can understand what's going on from the mode's name.

**Comment by sprangg** [comment]
Ok, sadly I have to say I just discovered a downside to personal logs being available at all times: Team drafts.

If the participants' personal logs are available to team drafters, the team can pool their logs after the draft and deduce all the picks of their opponents, apart for their first picks from pack. This doesn't seem like a good thing for the health of the format.

What do you think would be a good solution? In my opinion the personal logs should be excluded from team drafts, but this would of course introduce an inconsistency.

**Comment by Senryoku** [comment]
Since it's theoretically possible for players to write down each pick manually, I'd say it's not a huge issue, but I agree that it's more obvious in team draft.
Rather than silently disabling personal logs in team draft, I'd add another, separate, setting to explicitly disable them. It also has the advantage of making every option listed by @tooomm possible, while being somewhat simpler imo.
![image](https://user-images.githubusercontent.com/1338143/170823812-3fa026fb-79d6-4944-bbe4-cd9f5e6a57db.png)

**Comment by sprangg** [comment]
That's a great solution that should solve every problem situation!

**Comment by tooomm** [comment]
>Your list is a little too long for my taste

I know, I could not come up with shorter terms that are self speaking and on point. I used a shorter label to mitigate this a bit.
>![](https://user-images.githubusercontent.com/1338143/170822357-96d3e577-041a-4476-a874-89db2208cfd7.png)

That looks good and is definitely an improvement. Still don't think "owner" is obvious for "session owner", but I get your point.

<br>

Not a fan of private logs. But as long as they can be disabled in normal drafts as well, it's ok IMHO.

<br>

>There's a tooltip that tells what the "Owner only, delayed" mode does. I agree that based simply on the name it's hard to decipher but the tooltip tells all that's needed.
>The tooltip is a bit far indeed but noticeable enough imo and a sufficient explanation.

On big screens it can be quite far away, but the main point is that a tooltip should not be mandatory to correctly understand certain options.

**Comment by Senryoku** [comment]
I have a first version available here: https://mtgadraftbeta.herokuapp.com/
I'd be grateful if you could give it a test and report any bugs or concern you may have with it.

**Comment by sprangg** [comment]
Thanks, works great for the most part! We'll be doing a test draft with the "Everyone, on owner approval" mode in a few minutes, with personal logs enabled.

Here's the results of my quick testing:
- The "Everyone" mode works as intended, i.e. the same as before, with or without personal logs enabled.
- The "Everyone, on owner approval" mode works, except there's a download-button that's visible (to both the owner and the other players) before the logs are unlocked . By clicking it the owner (not the other players) can download the full log file and look at everyone's picks with a text editor. If you import this downloaded file to mtgadraft, you can't view everyone's picks there though.
- "Owner only" mode works, but when personal logs are disabled it adds an empty log into the log history of the players who aren't the owner (in non-beta this empty log doesn't get added to the log history).
- Same for the "No-one" mode, works ok but with personal logs disabled adds an empty log to the log history of all the participants.

**Comment by tooomm** [comment]
>I'd be grateful if you could give it a test and report any bugs or concern you may have with it.

Quick feedback:
- UI looks good. In combination with the tooltips, there are all needed information available.
- The session owner should not be able to download logs until he unlocks and shares them with all other players in the session.
- Disabling private logs and changing the setting to `Everyone, on owner approval` is not remembered. Every time I load the page, it's back to defaults.
- I did not test the various combinations.

**Comment by Senryoku** [comment]
Thanks for the feedback.

I wasn't too sure what to do about the download button, it's now disabled for not-yet-shared logs.

I choose to change the behavior slightly to always have a log, even it doesn't hold any card information. It's more consistent, let you keep a trace of your games and more importantly allow players to share their decks there (only the hashes if they don't have access to the full log).

> * Disabling private logs and changing the setting to `Everyone, on owner approval` is not remembered. Every time I load the page, it's back to defaults.

It's the case for every session related setting, I agree there's possible improvements here, but this is another topic.

**Comment by sprangg** [comment]
Since the download button is disabled now until the logs are unlocked, I'll be closing this! Many thanks for the implementation!
