### ISSUE TITLE
Seeing cards' oracle text

### ISSUE THREAD

**Issue by sprangg** [Senryoku/MTGADraft#331]
Especially when drafting some older cards, it would be a useful feature to be able to see their oracle text, due to there sometimes being large differences between the original and the oracle text (creature type updates etc.).

The oracle text doesn't need to be something that jumps at you and it would be ok to be behind a keypress or such. The feature would only be needed when checking the occasional card, not every card in the pack.

**Comment by Senryoku** [comment]
Started working on a solution here: [DisplayOracle](https://github.com/Senryoku/MTGADraft/pull/332)

**Comment by Senryoku** [comment]
871af095bf42a0301801556ae3ee7695631c9ae2
