### ISSUE TITLE
Raising the max commons per pack from 16 to 20

### ISSUE THREAD

**Issue by sprangg** [Senryoku/MTGADraft#354]
Hey there! Could the max commons per pack be raised to 20? Currently it's 16, and it's a little too low for what we'd like to use in our group.

20 would also make sense in that it's the current maximum number of cards in official wotc packs, i.e. it's the size of the Commander Legends packs.

Edit: And of course this would also affect the other rarities too, by extension.

**Comment by Senryoku** [comment]
Sure, the limit was arbitrary, I'll increase it.
Note that you can force any positive number by typing it in instead of using the arrows, it's just a hint for the browser (at least it works in Firefox).

**Comment by sprangg** [comment]
Thanks for the quick response! And for the hint of being able to type in any number, I didn't realize that! That concludes this case. 😊
