### ISSUE TITLE
feature request- pause screen

### ISSUE THREAD

**Issue by radiasian** [Senryoku/MTGADraft#359]
Hi!

I'm using mtgadraft to cast some drafts, and in between each pack I'd like to pause the draft and look over each person's picks. The current problem is that the pause screen blocks a lot of the picks. Would it be possible to get rid of the pause screen popup without resuming the draft? perhaps an alternate "start' button so you can x out the pause screen?

Thanks! MTGAdraft.tk is an incredibly cool tool, thank you for developing it!

**Comment by Senryoku** [comment]
Hello @radiasian!

This is definitely possible, but I'd like to better understand your use case before making any changes. Are you using the spectator mode to review picks? Are you coaching the other players during the draft?
I'm wondering if simply removing the timer (by setting it to 0) would solve your problem?

**Comment by duelcastermage** [comment]
I can answer for radiasian - I was involved in that draft. Yes, removing the pause screen just for the spectator seat solves the problem. He set up the draft as a host/spectator (only) and was streaming the progress with commentary in real time. He focused on just one player in throughout most of the pack as it was being drafted, but wanted to pause after each pack to review the pools of each other player at the table. The big square popup that resulted on pausing ended up blocking a huge chunk of the screen (we couldn't see players' 5- and 6- drops, for example), and the dimming effect further made it difficult to see the pools of drafted cards.

I think your solution probably already addresses the problem - thank you for doing that so quickly!

**Comment by Senryoku** [comment]
Thanks for the reply!
Yes, the dimming is gone too. I also updated the spectator mode to stay open after the draft has concluded.

**Comment by radiasian** [comment]
Holy cow you're fast! Thanks for the commit- I'll check it out when I get the chance.

**Comment by Senryoku** [comment]
> Holy cow you're fast! Thanks for the commit- I'll check it out when I get the chance.

Note that this isn't deployed yet, and I probably won't be able to deploy it before a couple of days.
