### ISSUE TITLE
Feature Request: Always-visible creature and land counts while drafting

### ISSUE THREAD

**Issue by duelcastermage** [Senryoku/MTGADraft#360]
It takes unnecessary effort to constantly have to click on the little pie chart icon to see how many creatures you've drafted at any given time. It would be fantastic to have a live count of your creatures (probably right next to the pie chart icon). Lands are less important, but still worth having a live count of too, I think.

Thanks!

**Comment by Senryoku** [comment]
I was just working on adding some headers to the Two-Rows displaying the creature count:
![image](https://user-images.githubusercontent.com/1338143/215769104-d2c60528-ac9a-47a5-91fc-46c37dae6675.png)
Maybe this is enough?

About the land count, I guess lands are alone in the first column most of the time, so you pretty much always have the land count there (or close enough).

**Comment by duelcastermage** [comment]
This is definitely an improvement! However, I think less savvy users would not see it very often due to the two-rows setting being off by default, and even if it's on, the actual count number is not in the place I'd expect. I still think a better spot (possibly in addition to what you show there) would be right up next to the pie chart icon.

**Comment by Senryoku** [comment]
Fair enough, I'll see if I can come up with something more elegant, but worse case scenario this will be in the next update:
![image](https://user-images.githubusercontent.com/1338143/215797125-4a0e6a61-ae44-4585-89ef-8105fb13bc9c.png)
