### ISSUE TITLE
Feature Request: Ability to resize/zoom out on deck and sideboard

### ISSUE THREAD

**Issue by duelcastermage** [Senryoku/MTGADraft#361]
The ability to zoom in/out on the current pack was a HUGE upgrade - kudos for that!

The problem now is, no such option exists for the deck pool and sideboard. The cards in the bottom sections are often too big to show everything on one screen. This therefore requires constant scrolling up and down, especially when dragging cards from your deck into your sideboard. Sometimes the cards are so big (relatively speaking), that you have to (slowly) push down on the bottom edge of your screen to even drag a card into your sideboard. This is especially true for smaller resolution monitors.

This makes streaming/recording drafts difficult, since it's harder to follow what a player is doing during the draft if we can't see their complete pool of drafted cards in addition to the current pack.

Having a slider for deck/sideboard zoom would be the most elegant solution to solve this problem, I think.

**Comment by Senryoku** [comment]
The size of cards in the deck/sideboard is driven by the number of columns, I cannot easily add a slider there. As a workaround you can try increasing the number of columns.
(I understand the opposite - where the size of cards would drive the number of columns - could be more intuitive, but it's way harder to implement correctly)

When drafting, have you tried collapsing the sideboard to the right of the screen? (Using this not-so-clear icon)
![image](https://user-images.githubusercontent.com/1338143/215787514-3f5c85f9-3e43-46cc-bdce-bf3c1280dd2c.png)
Note that you can also simply click on a card to swap it between main and sideboard.

**Comment by duelcastermage** [comment]
Ah ok, those workarounds actually do a good job of doing what I was asking for - thanks!

I will say though that they are not very intuitive - I've used mtgadraft many, many times and did not even see/think of doing either or those things to help with the problem.

**Comment by Senryoku** [comment]
I agree this is not very intuitive, but it was the best solution I found at the time that was both customizable and - perhaps more importantly - sufficiently robust.

I can see myself trying different things later on, but I'm closing this for now!
