### ISSUE TITLE
Randomize seating order on draft start ON by default

### ISSUE THREAD

**Issue by duelcastermage** [Senryoku/MTGADraft#362]
I think it makes more sense in more cases to have this option enabled by default. Most drafts I can think of will not want the order of player seating determined by the order of when they joined using the link. It's sometimes hard to remember to change this setting, especially for new hosts. Thanks!

**Comment by Senryoku** [comment]
Actually, players are already randomly inserted in the table when they join, it's not based on the order of arrival.
I don't want to have it enable by default as I think it would cause more confusion than the alternative when ignored (especially for team drafts) and the default is already sufficiently random.

**Comment by duelcastermage** [comment]
Ah fair enough. I didn't realize players were randomly inserted when they join. That makes sense - you can ignore my request :)
