### ISSUE TITLE
Feature Request: Better Integration with Cubecobra for "Custom Set List with Rarities"

### ISSUE THREAD

**Issue by duelcastermage** [Senryoku/MTGADraft#365]
Last night I tried to draft a custom set (with rarities) that a friend of mine built on cubecobra. Here is the link to it for this example: https://cubecobra.com/cube/list/3bxpd

The list is broken out by rarity in categories there (Common/Uncommon/Rare/Mythic). However, when I tried to set up the draft on mtgadraft (Settings > Custom Card List > Import from CubeCobra), the list loaded fine in the Settings area, but when I went to start the draft, I got an error which said:

> Error Generating Boosters. Not enough cards (265/360) in custom list.

I think mtgadraft somehow(?) assumed this was a typical singleton cube even though the "Custom Card List" box was ticked. Anyway, the rarity categories did not carry over from CubeCobra. We had to do a massive workaround to get it to work.

Any way we can get mtgadraft to automatically parse rarity categories from CubeCobra so text file manipulation or other workarounds are not necessary to draft these type of sets? Thanks!

**Comment by Senryoku** [comment]
The import from CubeCobra feature is based on their .txt export (basically [this file](https://cubecobra.com/cube/download/plaintext/62b8ed7f6956f6752026d661?primary=Color%20Category&secondary=Rarity&tertiary=Types-Multicolor&quaternary=Mana%20Value&showother=false) for your cube for example) and it does indeed treat it as a singleton cube (as this was the primary use of the feature).

I don't know which metadata you can attach to a cube on CubeCobra exactly, but as far as I know there's no way to export a cube with this information anyway. This includes "rarity categories from CubeCobra", so I don't think what you're asking is possible currently.

**Comment by Senryoku** [comment]
Closing this issue as there's not much I can do about CubeCobra integration right now.

We can discuss you last point in #363.
