### ISSUE TITLE
Spectating a draft with the "everyone, on owner approval" log mode

### ISSUE THREAD

**Issue by sprangg** [Senryoku/MTGADraft#368]
Hi!

We sometimes draft custom remastered sets on mtgadraft, where the creator of the set is equally cool with spectating the draft and playing it.

Now, we usually use the "everyone, on owner approval" logging mode when playing, which is fair for all the players. However in case we get an odd number of players the host of the draft (who is usually the creator of the set) may want to spectate the draft instead to make the player numbers even.

Here's the problem: It's easy to forget to change the logging mode away from "everyone, on owner approval" when changing yourself to a spectator, and then the host can't spectate the draft of their own set live and it's quite a bummer. The inability to spectate is not immediately obvious either, and we wouldn't want to restart the draft after everyone's made their first 1-2 picks.

Would it be possible to make a spectator host able to see all the logs and the live draft even when the "everyone, on owner approval" mode is on?

If not, a fine alternative would be to prompt the host of their inability to spectate the draft when they're about to launch the draft, so they can cancel the launch and change the setting.

**Comment by Senryoku** [comment]
Hello!

You're right, it make sense that a non-playing owner should be able to see the draft in this case. I changed this behavior in 4f44fe1.
Setting draft log recipients to 'No-one' will still prevent the spectator from seeing picks, but I think this one is fair.

**Comment by sprangg** [comment]
Sounds great, thanks!
