### ISSUE TITLE
[Feature] Download decks for MTGO trading

### ISSUE THREAD

**Issue by Senryoku** [Senryoku/MTGADraft#374]
> In order to facilitate Cube drafts on Magic Online, we often have to download all the drafted deck lists, so that we can trade with each drafter from our collection. This involves clicking on each drafter in the logs, selecting the format, and then downloading. 
> 
> Any chance you could add a feature that would allow downloading each of the drafter's pools, in a particular format, into 8 separate files with the drafters username as the name of the file? That would be so convenient!

This could be accessible from the draft log as "Download decks for MTGO trading"?
Also ignore added basic lands for this export?

**Comment by kylesnowschwartz** [comment]
What would also be useful is if we could just download it as card names without set/version information. Sometimes the card/set information gets other tools - like mana traders deck builder function - confused.

**Comment by Senryoku** [comment]
Commit 77f52f0 adds multiple actions to the draft log explorer:
![image](https://user-images.githubusercontent.com/1338143/219950411-9a281269-c3f0-46d2-bae7-b2dcb1feb97a.png)

I'm not thrilled with the UI, but it should be serviceable.

> What would also be useful is if we could just download it as card names without set/version information. Sometimes the card/set information gets other tools - like mana traders deck builder function - confused.

Currently "Card Names Only" gives the following format:
```
1 Vat of Rebirth
1 Planar Disruption
1 Aspirant's Ascent
1 Sinew Dancer
1 Escaped Experiment
1 The Mycosynth Gardens
1 Mesmerizing Dose
1 Vat of Rebirth
1 The Surgical Bay
1 Meldweb Curator
1 Adaptive Sporesinger
1 Leonin Lightbringer
1 Flensing Raptor
1 Bonepicker Skirge
1 Myr Kinsmith
1 Prophetic Prism
1 Meldweb Curator
1 Escaped Experiment
1 Mirran Bardiche
1 Duelist of Deep Faith
1 Duelist of Deep Faith
1 Unctus, Grand Metatect

1 Rebel Salvo
1 Vulshok Splitter
1 Against All Odds
1 Bladegraft Aspirant
1 Bladegraft Aspirant
1 Hexgold Halberd
1 Free from Flesh
1 Phyrexian Atlas
1 Cinderslash Ravager
1 Skyscythe Engulfer
1 Ezuri, Stalker of Spheres
1 Vulshok Splitter
1 Goldwarden's Helm
1 Maze's Mantle
1 Maze's Mantle
1 Cruel Grimnarch
1 Drown in Ichor
1 Drown in Ichor
1 Evolving Adaptive
1 Green Sun's Twilight
```
Is it good enough?

**Comment by Senryoku** [comment]
I wonder if this is better or even more confusing?
![image](https://user-images.githubusercontent.com/1338143/219951623-68046531-168a-4a2a-958f-b55e9bfe3a66.png)

**Comment by kylesnowschwartz** [comment]
I think the format dropdown with a checkbox for basics is very understandable! This will make it so much easier to download decklists for trading on MTGO, thank you.

**Comment by kylesnowschwartz** [comment]
One thing worth noting from a usability perspective is that there are now a lot of places where one can perform various kinds of exports and downloads of files and logs. I wonder if there should be a single 'export hub' with all the options contained in one place. It would obviously look different and have different options which depend on if you're in the Draft view or the Game Log view, but maybe there's something there...

**Comment by Senryoku** [comment]
> One thing worth noting from a usability perspective is that there are now a lot of places where one can perform various kinds of exports and downloads of files and logs. I wonder if there should be a single 'export hub' with all the options contained in one place.

I think it makes sense as it is, but I'm open to suggestions if you want to elaborate!

About this particular issue: I've deployed the update. Closing this as long as you don't find issues with the functionality :)

**Comment by kylesnowschwartz** [comment]
Works perfectly. You're awesome thank you!
