### ISSUE TITLE
[Feature] Chaos draft with the custom card list format

### ISSUE THREAD

**Issue by sprangg** [Senryoku/MTGADraft#378]
Chaos draft is already possible with the custom card list format, but the different kind of packs will appear an uneven amount, because the layouts are picked randomly.

I'd like to request an option to have each different layout be generated only once until all the layouts have been generated, basically how the "random set from card pool" chaos works with normal packs currently.

Considering this option would only be used alongside layouts, I think it might be best for this to be specified in the layout file itself instead of as a setting on mtgadraft. Could be specified on the first line of the file for example.

**Comment by Senryoku** [comment]
See #377
