### ISSUE TITLE
Hide booster customization fields by default

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#381]
In Sealed/Team Sealed, the customization options should not be visible always.

Idea: Hide the big, optional list of booster dropdowns behind a checkbox, similar to some options in settings (edit booster content and limiting duplicates)

`[ ] Customize the set of each booster (optional)`
![optional](https://user-images.githubusercontent.com/9874850/221410250-fdbed943-cd6c-4e15-a740-3896753f7eb8.png)

**Comment by Senryoku** [comment]
Implemented in fd3a2957826c751a5498d58e86a416e10e680e39
![image](https://user-images.githubusercontent.com/1338143/221580186-abb463e5-a598-46d5-a7af-e07160344ed0.png)
![image](https://user-images.githubusercontent.com/1338143/221580221-930ab004-f26e-4647-ba92-9a7f897293f9.png)
