### ISSUE TITLE
Dragging Ghost missing the first time on Firefox

### ISSUE THREAD

**Issue by Senryoku** [Senryoku/MTGADraft#52]
The first a card from the deck or sideboard is dragged in Firefox, the ghost does not appear.
So far the only lead I have is that a "transform: translateY(0px)" style is applied on drag - I guess by vuedraggable - and that it may mess with Firefox.
![GIF 23-06-2020 22-08-14](https://user-images.githubusercontent.com/1338143/85455550-4e386380-b59e-11ea-8f54-7c8f361ac25e.gif)
In the gif the card is dragged left and right for the first time since its instantiation: No visible ghost. The second time the ghost works just fine.

**Comment by joesaraceno** [comment]
I'm having trouble reproducing this on Firefox desktop (version 80.0.1). 

The first time I drag any card (and any subsequent times), the placeholder ghost shows up just fine as expected.

![missing_ghost](https://user-images.githubusercontent.com/45146247/93018296-e8032180-f58b-11ea-8410-b1f1728e99dc.gif)

**Comment by Senryoku** [comment]
I should have specified: This happens in the card pool component (Deck & Sideboard)

**Comment by tooomm** [comment]
I run again into this on Firefox 84.0.

**Comment by tooomm** [comment]
>I run again into this on Firefox 84.0.

Any idea @Senryoku? Did you fix this issue in November or did you maybe closed this on mistake?
I'm using Firefox 84.0.2 in between with the issue still exists on the current deployment.

**Comment by Senryoku** [comment]
I don't have the issue anymore using the exact same version of Firefox, on idea what's going on here =/
