### ISSUE TITLE
Order cards by rarity

### ISSUE THREAD

**Issue by aloisdg** [Senryoku/MTGADraft#7]
Hello,

Is there a specific reason why cards aren't ordered by rarity?

![image](https://user-images.githubusercontent.com/3449303/79040313-dd60ec80-7be7-11ea-982e-046f5272b3f9.png)

Is this a bug to tackle?

Cheers,

**Comment by Senryoku** [comment]
It's the "booster order" (only depends on how they are generated), the first card here is the "foil", that's intended :)

**Comment by aloisdg** [comment]
@Senryoku alright! Thank you for the input. They are no such things as foil in Arena. I know that they exists in real life booster though. Maybe it could be good to have an option to ignore them to be coherent with Arena draft.

**Comment by Senryoku** [comment]
It can be disabled in the session options 
![image](https://user-images.githubusercontent.com/1338143/79040754-15b5fa00-7beb-11ea-9827-713f81ace202.png)

**Comment by aloisdg** [comment]
Well. I should have search more. You rocks x)
