### ISSUE TITLE
"Auto. Land" feature doesn't consider already available basic lands

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#74]
If you pick basic lands out of a pack, they are not counted against the land count which gets confusing in deck building and makes the helpful auto land tool a bit less useful.

**Comment by Senryoku** [comment]
The auto land feature only fills the deck up to 40 cards when exporting and the displayed basic land count only cares about these added (and not shown) lands.
I get how this could be confusing, but I'm not sure how it can be improved?
I'm currently adding some statistics to the deck builder, maybe displaying the total number of basics (in deck and automatically added) there will help?

**Comment by tooomm** [comment]
>The auto land feature only fills the deck up to 40 cards when exporting and the displayed basic land count only cares about these added (and not shown) lands.

Exactly, it would be nice if it checks for other lands already in the deck, too.
Not only consider the card count of all cards in main deck to make it 40 in total.

>I'm currently adding some statistics to the deck builder, maybe displaying the total number of basics (in deck and automatically added) there will help?

Statistics are always nice! Excited to see what it will look like in the end, but having a total land count there (not only basics!) is good I think.

**Comment by tooomm** [comment]
This problem only occurs in sets which have basic lands in their boosters (e.g. M21).
For such sets, you end up with a few basics in your card pool to build the deck and a user can easily be confused. The mtgadraft page lets you choose the quantity of basics (or auto adds them) on export, but doesn't add them to the visible pool. In cases where you still see some drafted ones and one is not sure if or how they are considered things can get unclear.
In order to solve this there should all basic lands be shown (drafted + added ones), or none.

We could remove drafted basic lands from the pool after the draft portion is done for example to make a uniform experience across sets.
Same works if changing the basic count would add a visible card to your pool. The `Auto land` feature needs a little tweak in that case probably.

Both make the applied land logic more straight forward for users and should leave less/no obscurities behind.

**Comment by Senryoku** [comment]
> This problem only occurs in sets which have basic lands in their boosters (e.g. M21 _Update: After recent changes and fixes, now all booster contain basic lands again!_).

Agreed, this is more of a problem now that all packs have a land slot by default.

> We could remove drafted basic lands from the pool after the draft portion is done for example to make a uniform experience across sets.

This is probably the easiest route, but I fear that removing card automatically could prove confusing. What about a button in the future basic land control dropdown to remove them? (Only visible if there's basics in the deck/sideboard)
![image](https://user-images.githubusercontent.com/1338143/98850269-cd96d880-2454-11eb-80e1-63250025eaa7.png)

**Comment by tooomm** [comment]
>>We could remove drafted basic lands from the pool after the draft portion is done for example to make a uniform experience across sets.
>
>This is probably the easiest route, but I fear that removing cards automatically could prove confusing.

That is also true and a good point to think about. It should probably not be done silently.
I still think it can work as long as the user knows about it or is given an option.
For example, the `Done drafting` dialog/notification could hold a `Drafted basic lands are discarded --> ok` note or offers an `Discard basics for enhanced deck building --> yes/no` option if there are any (for normal draft at least).

>What about a button in the future basic land control dropdown (https://github.com/Senryoku/MTGADraft/pull/173) to remove them? (Only visible if there's basics in the deck/sideboard)
>![](https://user-images.githubusercontent.com/1338143/98850269-cd96d880-2454-11eb-80e1-63250025eaa7.png)

That would also work. But I assume it could feel a bit clunky as the user has to actively do something after the land confusion happened already. Wouldn't they most likely always remove them anyway... just to be sure? **I mean, I myself are still not sure if the drafted and displayed basics are considered for the calculation of auto lands. Or if they mess with the count and give me a less ideal distribution.**

I try to make the user not run into the initial problem at all:
*A newer user has two sources of basic lands with different visual handling and struggles to get the land count right.*
For me, the most obvious is to add lands visually to the deck pool and "work" with them, or you remove them completely and have a clean build environment. And I really like that the deck view is not flooded by a pile of lands.

Basic lands could also be striped from the boosters in the first place, but that could lead to other issues with certain sets.
A different option could be to replace basics with a non-pickable placeholder in a booster. That way we communicate with the user again, the booster content is not altered and there are probably less conflicts with other game modes or some sets.

I'm not sure what's the right (and not too complex) approach here.
User can still use the page just fine and work around issues, so there is no need to rush a solution.


### Summary of ideas so far:
- Remove basics automatically
    - Remove from drafted pool silently (after pick, or after drafting is done)
    - Remove from drafted pool at the end of drafting (show a hint in the `Done` notification or a pop-over in the upper right)
    - Remove from drafted pool after picking (show hint in a new info dialog or a pop-over in the upper right)
    - Remove from booster and never display
    - Remove from booster and replace with non-draftable placeholder containing a little hint
    - ...?
- Remove basics manually
    - Remove from drafted pool after clicking a button
    - Remove from drafted pool at the end of drafting (offer option in the `Done` notification)
    - Remove from drafted pool after picking (offer option in a new info dialog)
    - ...?
- Do not remove basics
    - Instead, rework `Adding lands` feature and visually add basics to the card pool (less streamlined build experience)
