### ISSUE TITLE
Ability to zoom cards

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#75]
Currently, cards are not shown bigger when you hover over them. They are only shown in full art.
For sets or cards that you don't know that well the text is still super small and can be difficult to read.

Maybe adding a zoom effect to the hovering as well would work?

**Comment by Senryoku** [comment]
I'm not a fan of an automatic zoom effect on hover (no real argument here, just personal aesthetic preference), so I tried triggering it on a right click:

![Uploading GIF 03-08-2020 15-32-51.gif…]()

Would that be an acceptable solution?

**Comment by tooomm** [comment]
That's a damn sweet solution, I even prefer that. Looks way easier to read and people just don't use it if they don't like/need it. Arena users are also used to the right click zoom already. 👍 

Do you have to click next to the card to make it disappear? Just move the mouse away? ...

Can you apply that to the drafting section as well?
There is a tiny zoom on hover already - not enough for proper reading though.

Another nice improvement! :)

**Comment by Senryoku** [comment]
You can either right click again or just move the mouse away to make it disappear.
I'll try to add that to the drafting part too :)

**Comment by Senryoku** [comment]
Addressed by 75e8893b0969a194f725fdf36d7b2c7630ca3fc7
Leaving this issue open for now in case we have more feedback on that feature.

**Comment by tooomm** [comment]
Does it also work for the collection by the way? :)

**Comment by Senryoku** [comment]
Yes :)

**Comment by tooomm** [comment]
I like it a lot, zoom is kinda big but that's not bad.

But what I recognized is that the zoom behaves different in the pick area during draft and in the collection stats than in the deck and sideboard section.
For the first two the zoom will be centered relative to your mouse click, for the later the zoom grows to the bottom.

**Comment by Senryoku** [comment]
Yeah I started smaller but figured that bigger couldn't really hurt while too small could render it useless. I used a rather random scale factor so If you know of any metrics I could base the size on, I'm interested!

Difference in behaviour stems from the way card column are rendered: The transform origin actually doesn't change, it's the element centre. Card arranged in columns are 25px tall and overflowing. I didn't think this was a problem so I haven't even try to fix it but I feel like it could be kinda cumbersome, unless we change the transform origin to the top of the card everywhere which is not desirable imho.

**Comment by tooomm** [comment]
That makes sense.
Actually, after testing it a bit... your scale (1,75x) is a good value. Even planeswalker with a lot of text are readable.
Sometimes the zoomed card can be cut off on the edges (e.g. zooming a card in the first column while deck building), but that's no deal breaker either.

The overall feature is great!
