### ISSUE TITLE
Set's title mutates with action

### ISSUE THREAD

**Issue by aloisdg** [Senryoku/MTGADraft#8]
Hello,

A screenshot is better than thousand words:

Here selected has no background:

![image](https://user-images.githubusercontent.com/3449303/79040713-c4a60600-7bea-11ea-952b-697455e05e29.png)

Here remove as a background but we clip the set title:

![image](https://user-images.githubusercontent.com/3449303/79040750-0fc01900-7beb-11ea-94b7-8c83f52f5492.png)

Some ideas:

* Add more space so everyone can have its own space.
* Use a "check" icon for selected and a "trash"  icon for remove

Since we are using font-awesome:

- [check](https://fontawesome.com/icons?d=gallery&q=check)
- [trash](https://fontawesome.com/icons?d=gallery&q=delete)

**Comment by Senryoku** [comment]
Agreed, does f1ff8dd54b1a1504cb914a8a01911a8f8abdef9e do the trick?

**Comment by aloisdg** [comment]
Should do. You can roll with it. A screenshot would be useful though ;)

**Comment by Senryoku** [comment]
Indeed!
![image](https://user-images.githubusercontent.com/1338143/79070403-e7611900-7cd5-11ea-9983-441d82ba683c.png)
