### ISSUE TITLE
"Restrict to collection" is not properly working

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#82]
It always shows `x have uploaded their collection.` and displays the green book for me when I join the site.
It doesn't matter if the "Restrict to Collection" check box is active or not. It correctly remembers its former state on join though.

But I always have to check and uncheck the box again to correctly update its state and make it display the yellow book and `...but are not using it.` message.

Using FF 79.0

**Comment by Senryoku** [comment]
Good catch.
Should be fixed by 7c28dbeb0040231d546bcf90b93e326709a5f0bd

**Comment by tooomm** [comment]
Thanks for the quick fix, will happily revisit after you deployed the change.

**Comment by tooomm** [comment]
Seems to work now!
