### ISSUE TITLE
Add set's icon to each set in the set combobox

### ISSUE THREAD

**Issue by aloisdg** [Senryoku/MTGADraft#9]
Hello,

Some new players aren't may mix set name (e.g. Ravnica block). I think we could enhance the UI by adding set's icon to each set in the set combobox. What do you think?

![image](https://user-images.githubusercontent.com/3449303/79040910-2fa40c80-7bec-11ea-9fd8-70aab25bc9cd.png)

It would take a bit more space though. It could be problematic.

related to https://github.com/Senryoku/MTGADraft/issues/8

**Comment by Senryoku** [comment]
IIRC I tried to do it but had some issues with vue-multiselect, or it was just to save space, I don't remember. Give it a try if you want!

**Comment by wrmacrae** [comment]
https://github.com/Senryoku/MTGADraft/pull/42
