### ISSUE TITLE
Request: Rochester draft

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#90]
https://magic.wizards.com/en/articles/archive/feature/rochester-draft-primer-2005-01-21
https://mtg.gamepedia.com/Rochester_Draft
https://www.youtube.com/watch?v=2rGoY4A4isg

I saw that Winchester draft, a combination of Rochester and Winston is on your list already...

**Comment by Senryoku** [comment]
Tentative implementation in 7a7034e393854cd7611ae1c8ca59ebf2c8acd506

**Comment by tooomm** [comment]
👍 

However, you don't want to implement Winchester any more?

**Comment by Senryoku** [comment]
Not right now, just trying to keep the scope of the project in check :)
