### ISSUE TITLE
Discord link is broken

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#99]
In the free response section of Survey #1, "ur discord has an invalid link and should be on the frontpage, people clearly use this website so u should build a community discord". I tried it and it didn't work for me either. Here's a link that should send people to General and never expire: https://discord.gg/mNJWQTB

**Comment by Senryoku** [comment]
I already updated the link (with one that doesn't expire this time). Just checked it and it is working for me?

**Comment by wrmacrae** [comment]
Ah, okay, so here's what I saw:
1) click discord link in chrome
2) click a Continue to Discord button
3) web version of discord opens in an anonymous account that isn't in the MTGADraft room, which makes it seem like the invite link is broken.

But, I tried the same workflow with a newer link and got the same result. And putting either link straight into discord within the "Join a server" dialog works fine. So, I think this is actually a discord bug of some sort and not something we can fix on our end. All that said, we should close out, but I'll take a quick look at whether this is being tracked by Discord and if I can flag it with them.

I was thinking per your comment about an open-ended form to collect suggestions, that the ideal workflow would be that you could actually just fill in arbitrary text from the app and get it sent to discord as feedback (with some sort of ability to follow the conversation further, see replies, etc. and eventually join for real in Discord), but that's probably a lot of work for a relatively unimportant story.

**Comment by wrmacrae** [comment]
This sounds like a common problem on the internet: https://www.reddit.com/r/discordapp/comments/c9rf5j/cant_join_discord_servers_from_web_browser/

**Comment by wrmacrae** [comment]
Ooooh, so I think this is because I had the discord app open with my real account, and it was already in the server, but the misleading thing is that the browser ends up on a page with an anonymous account not in the server. I'll explain all of this to discord in a support ticket.
